### ISSUE TITLE
SNOW-1017575 github.com/form3tech-oss/jwt-go is deprecated

### ISSUE THREAD

**Issue by tomas-karnagel** [snowflakedb/gosnowflake#1037]
Hi there,
It's not really a bug but also not a feature request.

We noticed that the snowflake driver uses github.com/form3tech-oss/jwt-go in the auth.go file and this project is deprecated and didn't get any updates in 2.5 years.
This is a potential security risk.

The more up to date thing to use is github.com/golang-jwt/jwt.

Thanks.
Tomas

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for calling this out, we'll review and see how to best proceed

**Comment by sfc-gh-dszmolka** [comment]
fix on PR https://github.com/snowflakedb/gosnowflake/pull/1117 which is now merged and will be part of the next upcoming release cycle of 2024 April, probably around next week

**Comment by sfc-gh-dszmolka** [comment]
released with 2024 April release cycle, version 1.10.0
