### ISSUE TITLE
SNOW-1020361 Unable to insert a UUID/byte array into an existing table

### ISSUE THREAD

**Issue by madisonchamberlain** [snowflakedb/gosnowflake#1041]
I am unable to insert data into a table with a byte(16) column. If I run the following two queries through conn.Exec through the driver, I will always get the following error.

Function to generate a UUID byte array 
```
func NewUuidBytes() []byte {
	u := uuid.New()
	return u[:]
}
```
Now I create a table with one BINARY(16) column: 
```
ID_COL_NAME :+ "ID"
createTableQuery := fmt.Sprintf(
	"CREATE TABLE IF NOT EXISTS %s ("+
		"%s BINARY(16) NOT NULL PRIMARY KEY, "+ // 16-byte UUID
		")",
	tablePath,
	ID_COL_NAME,
)
_, err := conn.QueryContext(ctx, createTableQuery)
```
Now I try to insert a row...
```
AddRowQuery := fmt.Sprintf(
	"INSERT INTO "TESTDB"."TESTSCHEMA"."TEST_TABLE_1706289161310224000_1210730230567371133" (%s) VALUES (?)" 
		")",
	ID_COL_NAME,
)
AddRowArgs := NewUuidBytes()
_, err := conn.QueryContext(ctx, AddRowQuery, AddRowArgs...)
```
The add row will always fail with the following error  `100115 (22000): The following string is not a legal hex-encoded value: '<[]uint8 Value>'`

And if I have a BINARY column where I attempt to add a single BINARY value like `[]byte{byte(2)}` that works fine.

**Comment by madisonchamberlain** [comment]
For a standard sized UUID, I am not able to add it because the value is too large. To generate a stringUUID I am doing the following: 
```
func uuidBytesAsStr() string {
	return hex.EncodeToString(newUuidBytes())
}

func newUuidBytes() []byte {
	u := uuid.New()
	return u[:]
}

```
And this returns the error `100145 (22000): Binary value '3632633637373162636139653466643238393536383631343238316636663437' is too long and would be truncated` I am looking for a work around but I am not sure if there is one

**Comment by madisonchamberlain** [comment]
This is very strange, and maybe its a server issue. The column I have is Binary(16). If I take the argument I was passing in, and do a hex.EncodeToString on it, and then pass it through to the driver with 
```
fmt.Sprintf(
	"INSERT INTO %s (%s) (SELECT TO_BINARY(HEX_ENCODE(?,0), 'HEX'))",
	tablePath,
	sfEscapeIdent(ID_COL_NAME),
)
```
it always overflows. The issue is that I am writing to some tables which are already configured to be BINARY(16). This issue persists with and without specifying a 0. Do you think this is a server issue?

**Comment by sfc-gh-dszmolka** [comment]
nice; happy to hear you managed to get it working after all ! 
before answering the question, I'd like to test it with other drivers as well, need some time for that.

**Comment by sfc-gh-dszmolka** [comment]
this seems to work with the Python Connector simply with
```python
[..cut for brevity]
myuuidbytes = uuid.uuid4().bytes
..
  cur.execute(
    "INSERT INTO testbinary(uuid) "
    "VALUES(%s)", (
        myuuidbytes
    ))
```

without any casting needed. I'm checking further internally if this is some limitation or needs to be done differently in `gosnowflake`. Thank you for bearing with us ! Will keep this thread posted.

**Comment by madisonchamberlain** [comment]
Ok thank you! And thanks again for the workaround, much appreciated!

**Comment by madisonchamberlain** [comment]
> Hi @madisonchamberlain , I think the solution is mentioning correct type manually, can you verify if it works for you? https://github.com/snowflakedb/gosnowflake/blob/master/bindings_test.go#L164

Yes this works thank you! I didnt know we could manually specify the type and just pass one `?` into the sql statement.
