### ISSUE TITLE
SNOW-1045439 Timestamp_ntz column values are formatted with UTC timezone

### ISSUE THREAD

**Issue by sp35** [snowflakedb/gosnowflake#1050]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of GO driver are you using?
v1.7.1

   
2. What operating system and processor architecture are you using?
MacOS, ARM
   
3. What version of GO are you using?
run `go version` in your console
1.20

4. Server version:* 8.5.1

5. What did you do?
I'm reading a `TIMESTAMP_NTZ` column from a table in Snowflake through this package, but the values from this column are being suffixed with UTC, which incorrectly indicates that the timestamp is in UTC. Ex: `2024-01-14 14:00:00`
 value on Snowflake is formatted as `2024-01-14T14:00:00Z`

6. What did you expect to see?
I was expecting that the timezone component would be omitted, instead of being assumed as UTC: `2024-01-14T14:00:00`

7. Can you set logging to DEBUG and collect the logs?

   https://community.snowflake.com/s/article/How-to-generate-log-file-on-Snowflake-connectors
   
8. What is your Snowflake account identifier, if any? (Optional)

**Comment by sfc-gh-dszmolka** [comment]
Hi and thank you for reporting this issue, we'll take a look. Good catch;  indeed looks like we apply `.UTC()` when converting `TIMESTAMP_NTZ` columns with the Go driver.

**Comment by sfc-gh-pfus** [comment]
Hi @sp35 ! I dag a bit deeper and my findings are as follow:
1. We have two conflicting forces - one is Snowflake and another is Go SQL library. 
2. Snowflake documentation is very general and when we talk about drivers, their API or the language itself should be taken into account.
3. Snowflake has a type timestamp NTZ (no time zone), which you obviously use.
4. But golang `time.Time` is a type that always contains timezone (can't be created without timezone info).
5. Also, the `Scan` documentation clearly states:

> // Source values of type time.Time may be scanned into values of type
> // *time.Time, *interface{}, *string, or *[]byte. When converting to
> // the latter two, time.RFC3339Nano is used.

When you check how the mentioned format is defined, you can see that it contains timezone:
> RFC3339Nano = "2006-01-02T15:04:05.999999999Z07:00"

So the driver behaves according to Go SQL standard. Even Snowflake allows adding timezone info into timestamp NTZ ([doc](https://docs.snowflake.com/en/sql-reference/data-types-datetime#timestamp-ltz-timestamp-ntz-timestamp-tz)):
> If the output format contains a time zone, the UTC indicator (Z) is displayed.

I believe that your case is that you select timestamp NTZ and scan it to string. Two workaround that I may suggest:
1. Scan to `time.Time` type and then format it on your own.
2. Use `TO_VARCHAR` function to format it on the backend. You can use parameter `TIMESTAMP_NTZ_OUTPUT_FORMAT` to specify format that you need.

**Comment by sfc-gh-pfus** [comment]
No news is good news - after two weeks of no new comments and thumb up as a reaction I take this topic can be closed.
