### ISSUE TITLE
Does setting CLIENT_SESSION_KEEP_ALIVE to true keep compute resources active and cost money?

### ISSUE THREAD

**Issue by lnashier** [snowflakedb/gosnowflake#1065]
### Issue description
It is unclear whether setting CLIENT_SESSION_KEEP_ALIVE to true keep compute resources active and cost money?

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this - setting [CLIENT_SESSION_KEEP_ALIVE](https://docs.snowflake.com/en/sql-reference/parameters#client-session-keep-alive) on the connection will cause the driver to send a request to `/session/heartbeat` on a predefined frequency, which is by default 1 hour but can be governed with the heartbeat frequency.

This doesn't use any compute resources, thus won't keep your warehouses active if there isn't any other query running on them and they're already suspended or set to auto-suspend, thus won't cost any extra money.

I would also like to encourage you to take a look at our [Community Forums](https://community.snowflake.com/s/) where there's an active community and can discuss various array of topics like this.

Hope this helps - marking this Issue as closed for now.

**Comment by lnashier** [comment]
Thank you @sfc-gh-hchaturvedi for the response. 

Also, my apologies for posting the question here and in other repos instead of community forums as I was not quite sure where to ask. Thanks for sharing the links for future reference.
