### ISSUE TITLE
Make logging optional

### ISSUE THREAD

**Issue by disq** [snowflakedb/gosnowflake#111]
Looks like logging is currently used only for debugging. Also, libraries using their own logging mechanisms are mostly frowned upon, here are some references:

- https://www.0value.com/about-Go-logging
- https://peter.bourgon.org/go-best-practices-2016/#logging-and-instrumentation
- https://github.com/go-kit/kit/issues/42

To remedy this, maybe we could create a compatible wrapper for glog and separate the actual glog import/usage from a no-op one using build tags. Say, a build tag named `sfdebug` would enable the actual glog wrapper and compile with glog, and without it would just use a null-logger (to satisfy the logging calls during compile) and not import glog.

This would also fix #106 since `flag.Parse()` is called by `glog`.

Would you consider such a solution? If so, we could send in a PR and go from there.

**Comment by smtakeda** [comment]
That sounds good. Please go ahead to file PR! thanks.
