### ISSUE TITLE
Bug in converter.go, line 170

### ISSUE THREAD

**Issue by murpheywa** [snowflakedb/gosnowflake#132]
### Issue description
converter.go, line 170 should store a nil back into the "dest" pointer parameter. Instead it sets the pointer itself to nil.
The end result is a column value from the prior row gets passed to caller's next row if the next row's column value is nil.

### Example code
Just change line 170 from

``` 
dest = nil
```

to

```
*dest = nil
```

### Error log
N/A

### Configuration
Both 1.1.0 and 1.1.1, any and all versions of golang and client OS's.

**Comment by smtakeda** [comment]
Thanks for reporting a bug.. WIP

**Comment by smtakeda** [comment]
The fix is merged with a test case. Get the latest code to have the fix for now.
