### ISSUE TITLE
Connection string is not properly unescaped

### ISSUE THREAD

**Issue by sirwart** [snowflakedb/gosnowflake#151]
### Issue description
For database drivers special characters in the password are normally url-encoded using percents. This lets you pass passwords that contain a '@' or ':' into the driver without causing issues. This driver just interprets whatever is between the '@' and ':' in the connection string as the password, which will cause failures if the user's password contains one of those characters.

**Comment by smtakeda** [comment]
The `dataSourceName` parameter of `sql.Open` is expected to be URI, hence it is an application's responsibility to escape parameters.
https://golang.org/pkg/database/sql/#Open
If it is not clear, I'll update the doc.

I understand `DSN` function, on the other hand, needs to escape parameters to construct DSN:
https://github.com/snowflakedb/gosnowflake/blob/master/dsn.go#L50

**Comment by sirwart** [comment]
I was originally escaping the parameters, but since they're not unescaped by parseDSN (and parseUserPassword in particular https://github.com/snowflakedb/gosnowflake/blob/master/dsn.go#L335) I can't connect with a password with special characters.In the screenshot below is both my original code that I commented out since didn't work, and my unescaped code that will work unless the password contains a '@' or ':'.

![screenshot 2018-02-26 15 56 04](https://user-images.githubusercontent.com/830101/36702825-9350721a-1b0d-11e8-9ce0-920b51405842.png)

**Comment by smtakeda** [comment]
Oh, ParseDSN is supposed to escape them. Fixing.

**Comment by sirwart** [comment]
Thanks @smtakeda, it's working great now!
