### ISSUE TITLE
Implement UUIDv4

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/gosnowflake#173]
gosnowflake depends on the third party UUID library (satori and Google) for the request id, which is used to track the client request. It is pain when the UUID breaks the API compatibility like the event happened half year ago on https://github.com/satori/go.uuid, so it would be nice to have our own UUID Implementation based on https://tools.ietf.org/html/rfc4122.

The requirement is not performance and resource intensive. UUID v4 should be good enough.

**Comment by sfc-gh-jbahk** [comment]
recreate jira

**Comment by sfc-gh-jbahk** [comment]
Done.
