### ISSUE TITLE
How do you quote identifiers?

### ISSUE THREAD

**Issue by bobzoller** [snowflakedb/gosnowflake#174]
### Issue description
I expected the API to have a way to quote identifiers (like table names), but it does not appear to.

### Example code
I want to do something like this:

```go
table := os.Getenv("TABLE_NAME")
query := fmt.Sprintf("SELECT id FROM %s WHERE FOO=?", snowflake.QuoteIdentifier(table))
```

**Comment by smtakeda** [comment]
can your problem be solved by direct binding the table name?
```
db.Query("SELECT id FROM identifier(?) WHERE FOO=?", table, value)
```
See https://docs.snowflake.net/manuals/sql-reference/identifier-literal.html for binding identifier.

**Comment by bobzoller** [comment]
ah!  yes that works, thanks.
