### ISSUE TITLE
Support for keypair authentication

### ISSUE THREAD

**Issue by Preston4tw** [snowflakedb/gosnowflake#179]
Placeholder issue. Keypair auth would be nice to have. It looks like the python implementation is here https://github.com/snowflakedb/snowflake-connector-python/blob/master/auth_keypair.py.

**Comment by smtakeda** [comment]
Added this to the internal backlog.

**Comment by smtakeda** [comment]
Released as a private preview. https://github.com/snowflakedb/gosnowflake/tree/v1.1.11

@Preston4tw try and let us know if you have questions.
