### ISSUE TITLE
CustomJSONDecoder missing millions of rows

### ISSUE THREAD

**Issue by coolaj86** [snowflakedb/gosnowflake#209]
### Issue description

I had performance issues (well, memory issues) with a database that had 5 million rows (memory usage ballooned to ~2GB), so I turned on `CustomJSONDecoderEnabled` and set `MaxChunkDownloadWorkers = 4` (not sure if that's a reasonable number or not).

Instead of getting 5 million rows back (`rows.Next()` from sqlx), I only got around 1.5 million.

### Example code

This is two or three snippets of code pasted together, but it should include all relevant pieces.

```go
	sf.CustomJSONDecoderEnabled = false
	sf.MaxChunkDownloadWorkers = 2

	db, err := sqlx.Open("snowflake", dburlstr)
	if err != nil {
		return nil, err
	}
	db.SetMaxIdleConns(5)
	db.SetMaxOpenConns(15)
	db.SetConnMaxLifetime(10 * time.Minute)

	defer db.Close()

	// remove SQLi security checks for brevity

	rows, err := db.Queryx(fmt.Sprintf(`SELECT * FROM %s`, id))
	if err != nil {
		return
	}

	// Write the CSV header
	colnames, err := rows.Columns()
	if err != nil {
		return
	}
	csvw := csv.NewWriter(out)
	err = csvw.Write(colnames)
	if err != nil {
		return
	}

	// Write each CSV row (as type string)
	numcols := len(colnames)
	rowstr := make([]string, numcols)
	for rows.Next() {
		var row []interface{}
		row, err = rows.SliceScan()
		if nil != err {
			return
		}
		for i, j := range row {
			switch v := j.(type) {
			case string:
				rowstr[i] = v
			case fmt.Stringer:
				rowstr[i] = v.String()
			default:
				rowstr[i] = fmt.Sprintf("%v", v)
			}
		}
		err = csvw.Write(rowstr)
		if nil != err {
			// must close rows if not read to completion as per sqlx docs
			rows.Close()
			return
		}
	}
	csvw.Flush()
```

### Error log

No errors that I'm aware of.

No rows are missing when run without the memory efficient JSON decoder.

### Configuration
*Driver version (or git SHA):* v1.1.15

*Go version:* go1.11.4

**Comment by mhseiden** [comment]
We have a bug fix to commit for this optimization. Will open a patch today or tomorrow 🙂

**Comment by coolaj86** [comment]
Many thanks!
