### ISSUE TITLE
release v1.1.16

### ISSUE THREAD

**Issue by coolaj86** [snowflakedb/gosnowflake#213]
Copying from https://github.com/snowflakedb/gosnowflake/pull/210 to make an explicit issue

I'm very interested in the fix in https://github.com/snowflakedb/gosnowflake/pull/210, could you tag a release for v1.1.16?

~~I've been googling a little bit to see how put a commit hash into `go.mod` when tags exist but I'm not super clear on that yet.~~

I was able to shim v1.1.16 by referencing the commit directly with `go get`:

```bash
go get github.com/snowflakedb/gosnowflake@011e99b734d76867766b3d5576450b9a2c835c3e
```

```
module example.com/pkgs/go-foobar

require (
	github.com/snowflakedb/gosnowflake v1.1.16-0.20190115205620-011e99b734d7
)
```

**Comment by smtakeda** [comment]
Getting approval of the release. Stay tuned.

**Comment by ankit-bhatnagar167** [comment]
Version v1.1.16 is released.
