### ISSUE TITLE
Building with go 1.11/go.mod yields "type jws.Claims has no field or method"

### ISSUE THREAD

**Issue by johnpena** [snowflakedb/gosnowflake#215]
### Issue description
Creating a new project from scratch using go 1.11 and go modules yields the following build errors:
```
# github.com/snowflakedb/gosnowflake
../../go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.1.15/auth.go:315:8: claims.SetIssuer undefined (type jws.Claims has no field or method SetIssuer)
../../go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.1.15/auth.go:317:8: claims.SetSubject undefined (type jws.Claims has no field or method SetSubject)
../../go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.1.15/auth.go:318:8: claims.SetIssuedAt undefined (type jws.Claims has no field or method SetIssuedAt)
../../go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.1.15/auth.go:319:8: claims.SetExpiration undefined (type jws.Claims has no field or method SetExpiration)
```

### Example code
I've recreated this problem in a very simple project called `snowflaketest` with these two files:

main.go:
```go
package main

import (
	"database/sql"
	_ "github.com/snowflakedb/gosnowflake"
)

func main() {
	_, _ = sql.Open("snowflake", "")
}
```

go.mod:
```
module snowflaketest

require (
	github.com/snowflakedb/gosnowflake v1.1.15
)
```

Run `go build main.go` and the error arises.

### Configuration
*Driver version (or git SHA):* `1.1.15`

*Go version:*  `go version go1.11.4 darwin/amd64`

*Client OS:* OSX High Sierra 10.13.6

**Comment by ChTimTsubasa** [comment]
It looks like it is complaining about the [JOSE jwt](https://github.com/SermoDigital/jose) module, which is a dependency in snowflake for KeyPair authentication. We have not used go module before to resolve dependency and our choice is go dep.

Is it a must for your case to use go module?

**Comment by johnpena** [comment]
Thanks for your response. Yes, this is a must for our applications, we can't change our dependency management for the sake of one dependency. Moreover, I'd expect more golang users will be using the go module system introduced in 1.11, as it's become the core standard for the language.

**Comment by ChTimTsubasa** [comment]
@johnpena 
A quick fix in your project to make it build is to change one line in your go.mod from
`github.com/SermoDigital/jose v0.9.1` 
to
`github.com/SermoDigital/jose v0.9.2-0.20180104203859-803625baeddc`

I will create a PR to enforce dependency management by go mod on our end.

**Comment by ChTimTsubasa** [comment]
Opened another issue to track the support for Go Modules. 
@johnpena Let me know if the quick fix mentioned earlier fits your requirement so that I can close this one.

**Comment by xoba** [comment]
i also +1 this issue, but bring up another issue as well, perhaps even a more important one, that the jose/jwt project itself is actually abandoned, so better maybe to find another provider altogether? see https://github.com/SermoDigital/jose/issues/43.

**Comment by smtakeda** [comment]
@xoba ok, filing a backlog for replacing jose.

**Comment by xoba** [comment]
great, thanks @smtakeda, could perhaps trivially even just be one of the forks people created based on and mentioned in SermoDigital/jose#43, which would be drop-in replacements. or, maybe now's an opportunity to choose more generally again.
