### ISSUE TITLE
Performance: Writing a few million rows can take hours.

### ISSUE THREAD

**Issue by solderjs** [snowflakedb/gosnowflake#223]
### Issue description

I'm writing ~200MB of data, about ~1MM rows in batches of 2500 and each batch seems to take forever.

Writing the whole set takes about 30 minutes.

I may just be doing something obviously stupid, but it seems like I should be able to do batches of 10,000+ and only have it take network time.

I also tried the naive approach of writing each row individually first. I know that wasn't faster, but I don't recall how much slower it was. In trying different batch sizes I didn't see much difference. The time seemed pretty linear.

### Example code
```go
	j := 0
	count := 0
	batch := 2500
	paramsSQL := []string{}
	results := []interface{}{}
	for {
		rowstr, err := csvr.Read()
		if err == io.EOF {
			break
		} else if err != nil {
			return err
		}

		qs := []string{}
		for _, v := range rowstr {
			qs = append(qs, "?")
			results = append(results, v)
		}
		paramsSQL = append(paramsSQL, "("+strings.Join(qs, ",")+")")

		j++
		count++
		// placeholder for committing a batch
		if 0 == count%batch {
			fmt.Printf("batch:%d count:%d\n", batch, count)
			colsSQL := `"` + strings.Join(headers, `", "`) + `"`
			insertStr := fmt.Sprintf(`INSERT INTO %s (%s) VALUES %s`, id, colsSQL, strings.Join(paramsSQL, ","))
			_, err = db.Exec(insertStr, results...)
			if err != nil {
				return err
			}
			count = 0
			paramsSQL = []string{}
			results = []interface{}{}
		}
	}
	fmt.Printf("(final) count:%d\n", count)
	if 0 != len(results) {
		colsSQL := `"` + strings.Join(headers, `", "`) + `"`
		insertStr := fmt.Sprintf(`INSERT INTO %s (%s) VALUES %s`, id, colsSQL, strings.Join(paramsSQL, ","))
		_, err = db.Exec(insertStr, results...)
		if err != nil {
			return err
		}
	}
```

I'm going to go back and make sure that the performance issue isn't on the side of reading the CSV. That would seem far less likely, but I'll do a sanity check.

### Configuration
*Driver version (or git SHA):*

github.com/snowflakedb/gosnowflake v1.1.16-0.20190115205620-011e99b734d7

*Go version:* go1.10, go1.11, go1.12

*Server version:*

Still need to check on this

*Client OS:*

Some sort of Linux. Not sure which.

**Comment by mhseiden** [comment]
@solderjs we saw issues like this as well, using `INSERT INTO`. We just switched to `COPY` statements and `snowpipe`, as the latency of those is significantly better for bulk / continuous loads.

**Comment by solderjs** [comment]
Hmm... it looks like `COPY INTO` doesn't support https? That's unfortunate because I'm actually dealing with 
https://docs.snowflake.net/manuals/sql-reference/sql/copy-into-table.html

And `snowpipe` requires preconfigured keypairs for API access, which is great, but unfortunately not something I can immediately add right now due to how other parts of the system I'm working with handle authentication.
https://docs.snowflake.net/manuals/user-guide/data-load-snowpipe-rest-load.html

**Comment by howryu** [comment]
@solderjs In which part of the doc indicating snowflake did not support https? All network go through https. And `copy into` is just like all other sql commands.

**Comment by solderjs** [comment]
@howryu The documentation enumerates s3://, azure:// and file://. It doesn't make any mention of https.

![Screen Shot 2019-03-27 at 4 47 50 PM](https://user-images.githubusercontent.com/122831/55117331-15b28d00-50b0-11e9-9cfc-a33014867e6d.png)

**Comment by smtakeda** [comment]
@solderjs Snowflake enforces HTTPS to all internet communications including S3 and Azure.

**Comment by solderjs** [comment]
@smtakeda I understand that, but that's a separate issue. I don't need S3 or Azure, I need bare, plain, https.

**Comment by smtakeda** [comment]
`COPY` commands uses always HTTPS between stages and Snowflake. The stages are on S3 or Azure.

**Comment by solderjs** [comment]
@smtakeda Right. What I'm saying is that I need a plain HTTPS stage where I give a file location url that the data will be fetched from. I need this:

```
COPY INTO [<namespace>.]<table_name>
     FROM "https://data.example.com/sets/foo123?access_token=abc123"
```

**Comment by smtakeda** [comment]
ah, I see. That's interesting... Well, this repo is for gosnowflake driver. can you please file a ticket to the support? `COPY` team should take care of it.

**Comment by solderjs** [comment]
Will do. Thanks.

**Comment by solderjs** [comment]
Would you mind pointing me to the support I should be contacting?

Also, for the sake of completeness, I did try:

``` sql
COPY INTO test_csv FROM 'https://example.com/assets/foo.csv'
```

which yielded

```
panic: 001011 (42601): SQL compilation error:
invalid URL prefix found in: 'https://example.com/assets/foo.csv'
```

I also tried

```
COPY INTO test_csv FROM '@./foo.csv'
```

which also didn't work.

The documentation is a bit confusing. Lot's of complex examples, but the simple ones don't seem to work as I expect.

**Comment by solderjs** [comment]
@mhseiden Could you show me an example of how you used `COPY INTO`? Everything that I've tried has resulted in various errors.

**Comment by mhseiden** [comment]
TBH you're best bet is probably to contact Snowflake Support about this. We're using Snowpipe which requires quite a bit more setup than a `COPY INTO` statement.

**Comment by howryu** [comment]
@solderjs We don't support `copy into t from @<url>`. Currently we support 
1) copy from an internal stage. i.e. `copy into t from @<stage_name>` where `stage_name` is the stage you created by running `create stage my_stage` https://docs.snowflake.net/manuals/sql-reference/sql/create-stage.html
2) copy form an external url, `copy into t from 's3://<bucket_name>/<path>'` 

In either case, load files are using https. I don't understand why you need an url in the form of `https://....`.

**Comment by solderjs** [comment]
@howryu 

1. That appears not to work. See https://github.com/snowflakedb/gosnowflake/issues/227
2. Because it's easy and it's fast. A webhook takes 2 seconds to set up, makes it dead simple to stream a file, and doesn't require copying a _whole_ file several times back and forth between cloud services. Right now we're dealing with small files that are only a few hundred MB, but our customer base is using multi-gigabyte files. We want a fast and smooth experience. https is the golden standard for secure and fast file transfer.

**Comment by solderjs** [comment]
Or are you saying that I can just use s3:// and point back to my own webhook that way?

If so, I totally missed that. I'm so used to services be locked into s3 (relying on it being that it didn't occur to me that I could just use `s3://example.com/foo.csv` and still get my webhook on my own server without actually having to implement any handshakes or specifics of the s3 protocol.

**Comment by howryu** [comment]
I am not familiar with webhook. But you can uploading files to your s3 location using https url. ( https://wincent.com/wiki/HTTPS_access_to_Amazon_S3_buckets ) then run copy command.

Let's say you have a bucket called `testbucket`. You can upload file by accessing `https://testbucket.s3.amazonaws.com/<key>` and then you can run copy command by `copy into t from `s3://testbucket/<key>`
