### ISSUE TITLE
Okta Authentication does not work

### ISSUE THREAD

**Issue by Veneciaaa** [snowflakedb/gosnowflake#228]
### Issue description
Setting Authenticator in Config as per [Godoc instructions](https://godoc.org/github.com/snowflakedb/gosnowflake#hdr-Connection_Parameters): "To authenticate through Okta, specify https://<okta_account_name>.okta.com (URL prefix for Okta)." However, it is using default authentication instead of Okta authentication because it is comparing Authenticator directly to "OKTA" in a switch statement [here](https://github.com/snowflakedb/gosnowflake/blob/master/auth.go#L223). It should be checking if the Authenticator _includes_ "OKTA".

### Example code
Proposed solution to check if Authenticator _includes_ "OKTA": https://gist.github.com/Veneciaaa/0e648e45a951d9cfe110fe4f86b37145

### Error log
"Incorrect username or password was specified" because it is using the default authentication method [here](https://github.com/snowflakedb/gosnowflake/blob/master/auth.go#L236) instead of Okta

### Configuration
*Go version:* go1.12.1

*Server version:* 3.26.1

*Client OS:* Max OS

**Comment by ChTimTsubasa** [comment]
Close this Ticket as it is addressed in #233
