### ISSUE TITLE
Need to know purpose of 'dep ensure' while "go get -u github.com/snowflakedb/gosnowflake"

### ISSUE THREAD

**Issue by aashakabragithub** [snowflakedb/gosnowflake#242]
### Issue description
I am running a standalone go code where I am connecting to snowflake and performing query on a table. Below are the steps that I performed -
1) go get -u github.com/snowflakedb/gosnowflake
2) run go code

It is working fine. So I am wondering what is purpose of 'dep ensure' for using snowflake go library? Is it really required?

Also, while referring to sample program under select1, I can see below code snippet
```
if !flag.Parsed() {
		// enable glog for Go Snowflake Driver
		flag.Parse()
	}
```
What is purpose of doing this? Because I am achieving results, without this code.

**Comment by smtakeda** [comment]
@ChTimTsubasa please take a look.

**Comment by ChTimTsubasa** [comment]
dep ensure is to install and verify the dependencies gosnowflake requires is available. In your case you don't need a `dep ensure` can fall into one of the 2 cases:
1. Your code base have the same dependency that gosnowflake requires.
2. Your dependency management tool automatically configure the dependency for gosnowflake.

The code snipped in select1 is to enable the glog for enabling logging. In your code it is also a good practice to provide some entry to enable glog, especially you want to know what went wrong inside the gosnowflake driver in the runtime
