### ISSUE TITLE
Question - Need to know latest Go version support

### ISSUE THREAD

**Issue by aashakabragithub** [snowflakedb/gosnowflake#245]
In README (https://github.com/snowflakedb/gosnowflake) it is mentioned, "The latest driver requires the Go language 1.11 or higher" whereas in CHANGELOG it is mentioned for "Version 1.1.18" to "Set the latest Go version to 1.12".

Our platform supports Go version 1.11.4, please suggest if latest snowflake go driver is compatible with the same.

**Comment by smtakeda** [comment]
Yes, go 1.11.x is supported by the latest gosnowflake driver. See the test target versions.
