### ISSUE TITLE
Question - Encrypted key for keypair authentication

### ISSUE THREAD

**Issue by patilpankaj212** [snowflakedb/gosnowflake#248]
Is encrypted key supported for keypair authentication? 

When I used "https://github.com/snowflakedb/gosnowflake/blob/master/rsa-2048-private-key.p8.enc" for testing purpose using code here "https://github.com/snowflakedb/gosnowflake/blob/master/priv_key_test.go" I am getting below error:

asn1: structure error: tags don't match (16 vs {class:1 tag:19 length:97 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pkcs8 @2

**Comment by smtakeda** [comment]
I don't think we support it today.
It would requires a passphrase parameter to decrypt a private key file.

**Comment by patilpankaj212** [comment]
Thanks @smtakeda. I found below issue on golang:

https://github.com/golang/go/issues/8860

It says that go doesn't have support for parsing encrypted PKCS8 private keys. I think this is the cause I got that error.
