### ISSUE TITLE
Question: Connection Validation

### ISSUE THREAD

**Issue by patilpankaj212** [snowflakedb/gosnowflake#251]
I am using below code to create a DSN string:

func getDSN(snowflakeConn *Snowflake) (string, error) {
	cfg := &sf.Config{
		Account:   snowflakeConn.Account,
		User:      snowflakeConn.User,
		Password:  snowflakeConn.Password,
		Warehouse: snowflakeConn.Warehouse,
		Database:  snowflakeConn.Database,
		Schema:    snowflakeConn.Schema,
	}

	dsn, err := sf.DSN(cfg)
	return dsn, err
}

if I do a db.Ping() by providing an incorrect "**Warehouse, Database name and Schema name**" no error is thrown. Are these values not validated while creating a connection? Is there a way to force validate these values also?

Plus, if the Account value is incorrect, I get below error:
timeout. err: Post https://ls24482.ap-southeast-.snowflakecomputing.com:443/session/v1/login-request?databaseName=BLAH&requestId=16ce5fe6-900c-420f-ac24-ca4debf46a9f&request_guid=77f68c2b-4b6a-4cb3-9f3f-c061f166332c&schemaName=TEST_SCHEMA&warehouse=COMPUTE_WH: x509: certificate is valid for *.snowflakecomputing.com, not ls24482.ap-southeast-.snowflakecomputing.com. Hanging?

But it took almost a minute to display this error. Could you please let me know if there a way to specify the connection timeout?

**Comment by smtakeda** [comment]
The validation issue is a regression. v1.3.0 will have the fix.

Try `LoginTimeout` parameter in `Config`:
```
LoginTimeout: 5 * time.Second
```

**Comment by patilpankaj212** [comment]
Thanks @smtakeda
