### ISSUE TITLE
Length is always '0' for TIME datatype

### ISSUE THREAD

**Issue by patilpankaj212** [snowflakedb/gosnowflake#252]
I have a column in a table with TIME(5) type. While querying on the table I get ColumnType.length as 0.

<database/sql.ColumnType>
name:"T1"
hasNullable:true
hasLength:false
hasPrecisionScale:false
nullable:true
length:0
databaseType:"TIME"
precision:0
scale:0

Shouldn't the length be 5?

**Comment by patilpankaj212** [comment]
@mknister ,

I created a table z3 with one column of type TIME. [create or replace table z3 (t1 time(5))]. I ran query "select * from z3" and wanted to get the precision for the TIME datatype (which is 5 in this case), but I couldn't get that info. Below is the sample code I tried with.

func main() {
	dsn, err := getDSN()
	if err != nil {
		fmt.Println(err)
		return
	}

	db, err := sql.Open("snowflake", dsn)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer db.Close()
	err = db.Ping()
	if err != nil {
		fmt.Println("error while ping request db", err)
		return
	}

	res, err := db.Query("select * from z3")
	if err != nil {
		fmt.Println("error while executing query", err)
	}

	cols, _ := res.ColumnTypes()
	for _, v := range cols {
		fmt.Println(v)
	}
}

**Comment by ChTimTsubasa** [comment]
@patilpankaj212 Hi. We are wondering what is the expected value for length of a TIME(5) type here? Is it going to be 5?

**Comment by patilpankaj212** [comment]
Hello @ChTimTsubasa,

Earlier I thought that I would get the precision of time datatype using the Length() function. Later I realized that it is only for text and binary types.

Thanks

**Comment by mknister** [comment]
Hi @patilpankaj212, length is just for text and binary and scale also does not have a value in terms of time/timestamp values, but we are working on seeing if we can return the precision value for time/timestamp values. That should have a value of 5 for TIME(5). This change hasn't been released yet, but I'll keep you updated.

**Comment by mknister** [comment]
Hi @patilpankaj212, in the next release, the precision value will be returned when ColumnTypes() is called.
