### ISSUE TITLE
Cannot insert more than 16384 records in one insert statement

### ISSUE THREAD

**Issue by patilpankaj212** [snowflakedb/gosnowflake#253]
I was trying to insert 50000 records in a single insert statement but I got below error:

001795 (42601): SQL compilation error: error line 1 at position 20
maximum number of expressions in a list exceeded, expected at most 16,384, got 50,000

Is this a limitation?

**Comment by smtakeda** [comment]
Yes, that's a single statement limitation.
Snowflake supports array binding, but we have not figured out how it can fit into the Go sql interface yet.

**Comment by patilpankaj212** [comment]
Thanks @smtakeda
