### ISSUE TITLE
us-west-2 default region

### ISSUE THREAD

**Issue by alldoami** [snowflakedb/gosnowflake#270]
When specifying a region, if the region you want is `us-west-2`, you don't want to specify it because it won't trigger the default code (where the default region is `us-west-2`). 

Reference to the default code:
https://github.com/snowflakedb/gosnowflake/blob/52137ce8c32eaf93b0bd22fc5c7297beff339812/dsn.go#L61

**Comment by sfc-gh-jbahk** [comment]
Hi, thank you for bringing this to our attention. We’ll do our best to fix it by our next release. Please note that the `region` parameter is deprecated and we will drop support of it in the near future.
