### ISSUE TITLE
Add support to return QueryExecutionID from results.

### ISSUE THREAD

**Issue by Jeremyyang920** [snowflakedb/gosnowflake#278]
### Issue description

We require the QueryExecutionID to come back from results.  I know that it comes with the python driver, but for business purposes we are bound to the go driver. Is there a way to allow the queryExecutionID to be returned?

**Comment by robbruce** [comment]
@Jeremyyang920 a very very hacky way to do it, not likely to be stable

```golang
queryID := reflect.ValueOf(conn).Elem().Field(2).Elem().Field(3).Elem().Elem().FieldByName("QueryID")
```

I think the limitation is imposed by the database/sql package
