### ISSUE TITLE
SNOW-144296: Multiple SQL statements in a single API call support

### ISSUE THREAD

**Issue by massousaC1** [snowflakedb/gosnowflake#287]
### Issue description
Currently, multiple SQL statements are not possible in a single API call. This is true even for simplistic _first_ statements such as `SET PARAM = 5;` which don't lend themselves to being executed in separate API calls. We are aware work is being done to address this but haven't seen any comment regarding Go drivers. We are curious if the issue has been resolved in subsequent releases of the Go package or is in your backlog with any intent to address it.

### Example code
```go
	// Execute the query and fetch rows into a cursor
	var rows *sql.Rows
        var err error
	if rows, err = db.Query(query); err != nil {
		log.Error("Unable to execute query", log.Items{"queryname": content, "query": query, "error": err})
		return
	}
	defer rows.Close()
```

### Error log
```
000006 (0A000): Multiple SQL statements in a single API call are not supported; use one API call per statement instead.
```
### Configuration
*Driver version (or git SHA):* v1.3.4

*Go version:* go1.13.1 darwin/amd64

*Server version:* 4.8.1

*Client OS:* MacOS 10.15.3

**Comment by sfc-gh-jbahk** [comment]
Hi @massousaC1, this feature is now available as per v1.3.8/
