### ISSUE TITLE
SNOW-153950: Rows.NextResultSet should return false at all times

### ISSUE THREAD

**Issue by sfc-gh-stakeda** [snowflakedb/gosnowflake#292]
### Issue description
It appeared the implementation of `Rows.NextResultSet` is wrong. It should return true if the next result set exists, but instead, it returns true if the next chunk is available. That's the implementation detail.
Since today the golang driver doesn't support the multiple statement/result set, it should always return `false`

### Example code
https://github.com/snowflakedb/gosnowflake/blob/master/driver_test.go#L1418
```go
		for rows.Next() {
			err := rows.Scan(&idx, &v)
			if err != nil {
				t.Fatal(err)
			}
			if cnt%1000 == 0 {
				glog.V(2).Infof("%v, %v", idx, v)
// WRONG: you should not call rows.NextResultSet in the middle of Next loop. 
                                  glog.V(2).Infof("NextResultSet: %v", rows.NextResultSet())
			}
			cnt++
		}

```

### Error log
If the number of rows is small enough to be included in the first chunk, the test case returns always `1` because `rows.NextResultSet` closes the row object before `rows.Next` reaches to the end.

### Configuration
*Driver version (or git SHA):*
378d5fc0e2522eee9c3d509702c8b12fcaa67ddf

*Go version:* run `go version` in your console
```
> go version
go version go1.14.1 darwin/amd64
```

*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10
Mac Catalina

**Comment by sfc-gh-jbahk** [comment]
This bug has been fixed in both single statement and multistatement queries as per v1.3.8
