### ISSUE TITLE
Cancel on Ctrl+C

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/gosnowflake#3]
### Issue description
When hitting ctrl+C, the query must stop.

**Comment by disq** [comment]
How is this the job of a database/sql driver? The user should capture ctrl-c (or any other exit/error event) and act accordingly, cancelling queries if needed.

**Comment by smtakeda** [comment]
Ah, I missed this item. will see when we can do this.

Basic idea is if a Ctrl+C event happens while running a query, the driver should submit cancel REST API to cancel the query in the server side.

**Comment by smtakeda** [comment]
PR #108 has changes for review.
