### ISSUE TITLE
SNOW-188697: Add ability to set client info (or reuse app info)

### ISSUE THREAD

**Issue by ryantxu** [snowflakedb/gosnowflake#329]
### Issue description
It would be great to control what shows up in the Client with more fidelity than "Go 1.3.8"  (especialy since I am running in go 1.4.1!

![image](https://user-images.githubusercontent.com/705951/91767461-054dee00-eb91-11ea-9956-1c9b0e98a72e.png)
### Example code
I have also tried chaning the applicaiton name in config... but that does not change anything either

```go
        cfg := &sf.Config{
		Account:      strings.Trim(account, " "),
		User:         strings.Trim(username, " "),
		Password:     password,
		Warehouse:    warehouse,
		LoginTimeout: time.Second * 5,
		Application:  "MyApplication",
	}
```

**Comment by sfc-gh-jbahk** [comment]
@ryantxu I believe the Client Info presented there is not the Golang version you have, but rather the driver version you are using

**Comment by sfc-gh-jbahk** [comment]
Is there a specific use case as to why you'd need to modify client information?
