### ISSUE TITLE
SNOW-294718: ocsp_response_cache.json error on import if file doesn't exist

### ISSUE THREAD

**Issue by burningalchemist** [snowflakedb/gosnowflake#390]
### Issue description

Hello,

If `ocsp_response_cache.json` doesn't previously exist, the driver responds with
```
ERRO[0000]log.go:120 gosnowflake.(*defaultLogger).Errorf failed to open. Ignored. open /path/to/Snowflake/ocsp_response_cache.json: no such file or directory
```

The error appears on the package import, and though is not fatal, still creates some worries on the user experience side. It's likely comes from oscp.go initOCSPCache() call ([link](https://github.com/snowflakedb/gosnowflake/blob/master/ocsp.go#L928)).
I'm using multiple drivers through `sql/database` in my package, so I can choose a connection, and `gosnowflake` seems to be the only library which produces a bit of noise, while not even being configured.

We potentially could do something of the following:
- try to create an empty `ocsp_response_cache.json` if nothing is found. We already do the same with a folder if it doesn't exist ([link](https://github.com/snowflakedb/gosnowflake/blob/master/ocsp.go#L927)). If file creation fails, it's reasonable to log it as an error;
- reduce log level from Error to Warning, since the error is still ignored ([link](https://github.com/snowflakedb/gosnowflake/blob/5ee1eee4677f66fd4fbb3068d18a7985a8d34191/ocsp.go#L725));

Otherwise, it would be great to get some advice from your side.
Thanks!

P.S. There were no issues before due to a different logging library used by gosnowflake. I guess the error just wasn't propagated. :)

### Example code
I can reproduce the issue with [gosnowflake/cmd/select1/select1.go](https://github.com/snowflakedb/gosnowflake/blob/5ee1eee4677f66fd4fbb3068d18a7985a8d34191/cmd/select1/select1.go) 

### Configuration
*Driver version (or git SHA):* master
*Go version:* 1.15.8 and 1.16
*Client OS:* macOS 10.15.7

**Comment by bradleyankrom** [comment]
I had the same experience today when trying to run a compiled binary on Ubuntu 16.04.

**Comment by sfc-gh-jbahk** [comment]
This fix has been merged and will be available in the next release. Thank you for bringing this to our attention.
