### ISSUE TITLE
SNOW-302103: Disabling OCSP cache does not stop noisy logging

### ISSUE THREAD

**Issue by rleighton** [snowflakedb/gosnowflake#403]
### Issue description
When SF_OCSP_RESPONSE_CACHE_SERVER_ENABLED is `false` the driver still logs output for failed actions.

### Error log
![image](https://user-images.githubusercontent.com/18419762/111869701-f2e1a900-8956-11eb-9f3f-396e506c36f9.png)

**Comment by serbantanasa** [comment]
It would be nice if this got fixed.

**Comment by tobier** [comment]
Need this to be fixed, slowly filling up logs when using gosnowflake in a periodical service.

**Comment by sfc-gh-jbahk** [comment]
This has been addressed and will be available in the next release. Thank you.

**Comment by jyxjjj** [comment]
Hello, i was using `InfluxDB/Telegraf`, I noticed a dir contains `ocsp_response_cache.json` was created by this repo, how can i disable it? `SF_OCSP_RESPONSE_CACHE_SERVER_ENABLED=false` is okay?

**Comment by sfc-gh-dszmolka** [comment]
that should do it, or you can even disable the whole OCSP checking mechanism and everything around it with `config.DisableOCSPChecks = true` 
(https://github.com/snowflakedb/gosnowflake/blob/v1.13.1/dsn.go#L85)
