### ISSUE TITLE
SNOW-354479: Snowflake sessionId should be explicitly int64

### ISSUE THREAD

**Issue by westernspion** [snowflakedb/gosnowflake#419]
https://github.com/snowflakedb/gosnowflake/blob/master/auth.go#L179

Should be explicitly set to an int64 since snowflake returns session IDs outside int32 bit range.

When compiled for 32bit systems, this is an issue.
`cannot unmarshal number 223909539689206 into Go struct field authResponseMain.data.sessionId of type int`

**Comment by sfc-gh-jbahk** [comment]
@westernspion this has been addressed and will be available in the next release.
