### ISSUE TITLE
SNOW-357277: Outdated changelog

### ISSUE THREAD

**Issue by prochac** [snowflakedb/gosnowflake#428]
Please update changelog, or delete it.
The current state doesn't look professionally.
It's untouched for two years and the value equals zero.

https://github.com/snowflakedb/gosnowflake/blob/master/CHANGELOG.md

**Comment by sfc-gh-jbahk** [comment]
Thank you for bringing this to our attention. We've removed the changelog; please refer to https://github.com/snowflakedb/gosnowflake/releases which delineates release notes per version.
