### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/gosnowflake#43]
### Issue description
We may want to have more examples in cmd/ directory.

**Comment by smtakeda** [comment]
This is more or less ongoing task. Removing from v1.0 project.

**Comment by igungor** [comment]
What do you think about moving the examples to a an [testable example](https://blog.golang.org/examples)? They could be part of the test suite (also CI can run them with 'go test').

**Comment by smtakeda** [comment]
Yeah, that would be a good idea. I just didn't have a chance to transform yet.
