### ISSUE TITLE
SNOW-378801: Getting 0/1 instead of true/false when querying on a column of boolean type

### ISSUE THREAD

**Issue by shubham00jain** [snowflakedb/gosnowflake#450]
### Issue description
When I query I get 0/1 instead of true/false in boolean type column.
Expectation : should get true/false instead.

### Configuration
*Go version:* go1.16.5
*Server version:* 5.25.0
*Client OS:* macOS 11.2.3

**Comment by sfc-gh-jbahk** [comment]
Can you provide an example? I'm unable to reproduce.

**Comment by shubham00jain** [comment]
Sorry my bad. Problem is solved now. Closing the issue.
