### ISSUE TITLE
Non-blocking polls for status of query

### ISSUE THREAD

**Issue by serbantanasa** [snowflakedb/gosnowflake#463]
### Issue description
We use AWS lambda functions to implement an async query interface. Roughly the flow is:

1. make async query, return query id to client
2. client polls for status of query using query id
3. when done, client uses query id to get results/errors

Currently, the only way to check (non-blocking) for completion using the go driver is to issue repeated sql queries against information_schema.query_history. By contrast, a method to accomplish this without queries [already exists in the python connector](https://github.com/snowflakedb/snowflake-connector-python/blob/master/src/snowflake/connector/connection.py#L1338). 

The current driver does actually already have a method that implements step (2.) called checkQueryStatus but it is private. By making this method publicly accessible (via a SnowflakeConnectionAPI interface), now step (2.) can be done w/out executing any additional sql query, making the entire operation cleaner and a LOT faster. 

We expect that many other goSnowflake users will find this useful in the future. 

### Example code

Implementation here:
https://github.com/snowflakedb/gosnowflake/pull/458

**Comment by sfc-gh-jbahk** [comment]
This has been addressed and merged. It will be available in the next release.

**Comment by serbantanasa** [comment]
Thank you!
