### ISSUE TITLE
User character length limit (64) exceeded by string ''

### ISSUE THREAD

**Issue by dhan-yext** [snowflakedb/gosnowflake#470]
### Issue description
I'm attempting to insert a slice of uuids into a temporary table in Snowflake. The table has a column for uuids: UUID
VARCHAR(64) NOT NULL. When I try to insert a particular slice of uuids into a temporary table, I get an error about the string '' exceeding the 64 character length limit. Before inserting a uuid into the slice, I'm checking that its length is 64 characters or less and that there are no invalid utf-8 characters. However, I am still consistently able to reproduce the issue, and this slice of uuids is not able to be inserted: [uuids.log](https://github.com/snowflakedb/gosnowflake/files/7033200/uuids.log)

### Example code
```go
        db := snowflake.SnowflakeConn()
	randTableNum := rand.Intn(10000)
	tempTableName := fmt.Sprintf("LOGS.%s_REQUESTS_UUIDS_%d", "api", randTableNum)
        ctx := context.Background()
	_, err := db.ExecContext(ctx, fmt.Sprintf(
		"CREATE TEMPORARY TABLE %s (UUID VARCHAR(64) NOT NULL)", tempTableName))
        glog.FatalIf(err)
        uuids := make([]string, 0)
        // exact slice of uuids attached above
	_, err = db.ExecContext(ctx,
		fmt.Sprintf("INSERT INTO %s VALUES ", tempTableName)+"(?)", gosnowflake.Array(&uuids))
	glog.FatalIf(err)
```

### Error log
```
  - 100074 (54000): User character length limit (64) exceeded by string ''
  File '9f89cc42-e81b-49c3-9452-255adfec2164/2', line 47697, character 1
  Row 47697, column "KNOWLEDGE_API_REQUESTS_UUIDS_8081"["UUID":1]
```

### Configuration
*Driver version (or git SHA):* v1.6.1

*Go version:* go1.16.5 darwin/amd64

*Server version:* 5.31.4

*Client OS:* macOS Catalina Version 10.15.7

**Comment by sfc-gh-jbahk** [comment]
Closing this as stale. We believe the issue to be fixed - please re-open if needed.
