### ISSUE TITLE
Panic in QueryStatus() Release 1.6.3 when SQL has a Syntax Error

### ISSUE THREAD

**Issue by rleighton** [snowflakedb/gosnowflake#476]
### Issue description
Any SQL with a syntax error (e.g,  `select from where`) will cause a panic in `QueryStatus()` in Release 1.63

### Error log
```
=== RUN   TestIntegrationExecuteQuerySyntaxError
    integration_test.go:325: testing locally
ERRO[0030]monitoring.go:152 gosnowflake.(*snowflakeConn).checkQueryStatus failed to decode JSON. err: json: cannot unmarshal string into Go struct field retStatus.data.queries.errorCode of type int 
--- FAIL: TestIntegrationExecuteQuerySyntaxError (4.51s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4b0d475]

goroutine 271 [running]:
testing.tRunner.func1.2(0x5396800, 0x632c660)
	/usr/local/Cellar/go/1.16.6/libexec/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc001109200)
	/usr/local/Cellar/go/1.16.6/libexec/src/testing/testing.go:1146 +0x4b6
panic(0x5396800, 0x632c660)
	/usr/local/Cellar/go/1.16.6/libexec/src/runtime/panic.go:965 +0x1b9
github.com/snowflakedb/gosnowflake.(*snowflakeConn).GetQueryStatus(0xc000130cc0, 0x596b2c0, 0xc0011d96b0, 0xc0010c6bd0, 0x24, 0x0, 0xc00108db30, 0x4012058)
	/Users/russell/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.6.2/connection.go:440 +0x95

```

### The Fix
This line:  https://github.com/snowflakedb/gosnowflake/blob/0cd53b222516a3c6265569049f852fe7b330fee6/monitoring.go#L84
  
Should be: `ErrorCode int `json:"errorCode,string"`

**Comment by rleighton** [comment]
The fix above applied here: github.com/rleighton/gosnowflake-1.62-patch v1.6.2-patch

**Comment by sfc-gh-jbahk** [comment]
I believe this has been fixed; SQL queries with syntax errors should not cause a panic.

**Comment by rleighton** [comment]
I’ll check against the latest release. The issue was handling the JSON, see
the fix

**Comment by sfc-gh-jbahk** [comment]
The JSON fix you proposed breaks the unmarshalling since the data parsed from the server side returns an integer and adding string in the JSON field isn't valid.

**Comment by rleighton** [comment]
No it does not. We are currently using a branch with this patch , since it
crashes for customers.

The fix allows a string or an int.

Please test it yourself

**Comment by rleighton** [comment]
What I think is happening is the internal api returns a string int code on
these errors. Using this tag let’s it work in this case.

We have extensive tests using the async api, without this change the driver
panics (or did, perhaps you change things on the server side) .

I tested the last release (from memory) still was crashing. I also
escalated this up thru folks we work with at sf.

I’ll test again tomorrow if you think it is fixed.

**Comment by rleighton** [comment]
Tested against v1.6.6, still crashes.

The fix specified above works and we have to keep a branch against this code since Sept 2021 because this has not been fixed.

By adding the `,string` to the Golang tag it allows string versions of the int. This is a 7 character change that fixes this.

Here is a stand alone program that demonstrates the bug: https://gist.github.com/rleighton/5a7fb249446a55b61a01656ca16369f6

**Comment by sfc-gh-jbahk** [comment]
`msg="failed to decode JSON. err: json: invalid use of ,string struct tag, trying to unmarshal \"\" into string" func="gosnowflake.(*snowflakeConn).checkQueryStatus"`
As mentioned, this is the error I get when I apply your fix.

**Comment by rleighton** [comment]
> `msg="failed to decode JSON. err: json: invalid use of ,string struct tag, trying to unmarshal \"\" into string" func="gosnowflake.(*snowflakeConn).checkQueryStatus"` As mentioned, this is the error I get when I apply your fix.

We have been using the patch for months on branch to get around this:
![image](https://user-images.githubusercontent.com/18419762/152655742-3fd4ad1b-8c1e-4787-a97f-8505da86c789.png)

**Comment by sfc-gh-jbahk** [comment]
The newest release changes the ErrorCode from an int to a string. Perhaps that suits your needs?

**Comment by rleighton** [comment]
It is not my needs , the driver panics checking status.

Does my gist work on the latest release? When I latest ran it it crashes

**Comment by sfc-gh-jbahk** [comment]
Your fix applied to the latest release produces the error message I sent earlier. I'll look into it some more later, thanks.

**Comment by rleighton** [comment]
Any luck? Just to be clear the "fix" only changes the JSON tag on that field to allow JSON ints with and without quotes. I did NOT change the type to string. We have been using this fix for months to avoid the crashes. You should be to run the gist above on the current release, see the crash, change the JSON tag adding ",string" to the end, re-run the gist and it works. I did exactly that when I developed the gist that demonstrates the crash.

**Comment by sfc-gh-jbahk** [comment]
@rleighton I am aware and did add the ",string" to to the end and it produces the error message I sent above; I also tried to apply your fix in your standalone program that was meant to demonstrate the bug and it produces the same error. The latest release also addresses the issue of the field ErrorCode within retStatus to be a string which sounds like it was the issue, if you'd like to try that.

**Comment by rleighton** [comment]
I’ll try the latest, Ty!

**Comment by rleighton** [comment]
Confirmed the latest release fixes this! Ty!. Closing.
