### ISSUE TITLE
No way to create an Array() of []Time with timestampTzType constants for bulk inserts with time fields.

### ISSUE THREAD

**Issue by triddin** [snowflakedb/gosnowflake#487]
### Issue description
Should be able to use bulk insert with array of `time.Time`, however the constants like `timestampLtzType` etc are private and we cannot create a bulk-compatible array.

Without specifying the `snowflakeType`, the input `[]Time` is returned which isn't bound to bulk inserts.

### Example code
```go
times := []time.Time{time.Now()}
columns := gosnowflake.Array(times, gosnowflake.timestampLtzType)
```

### Configuration
*Driver version (or git SHA):* v1.6.3

*Go version:* go version go1.16.7 linux/amd64

*Server version:* 5.38.0

*Client OS:* Ubuntu 20.04 LTS (focal)

**Comment by sfc-gh-jbahk** [comment]
Hi, can you raise a ticket with our support team? Thank you.

**Comment by sfc-gh-jbahk** [comment]
recreate jira

**Comment by sfc-gh-jbahk** [comment]
This has been addressed and merged. It will be available with the next release.
