### ISSUE TITLE
Update github.com/pkg/browser to 681adbf594b8 or newer

### ISSUE THREAD

**Issue by calvn** [snowflakedb/gosnowflake#498]
### Issue description
The current imported version of `github.com/pkg/browser v0.0.0-20210706143420-7d21f8c997e2` cannot be properly compiled for operating systems that are browser-unsupported (but should still be buildable) by `pkg/browser` due to a [declared but unused import](https://github.com/pkg/browser/blob/7d21f8c997e2ac35feaafc77d6078f606cfbe149/browser_unsupported.go#L7) in that particular commit. This causes projects that import this module to be unable to compile against certain operating systems as well.

### Example code
Sample build output for Vault against netbsd/386 without overriding this indirect dependency:

```sh
$ XC_OSARCH=netbsd/386 make dev
==> Checking that build is using go version >= 1.17.2...
==> Using go version 1.17.2...
==> Removing old directory...
==> Building...
Number of parallel builds: 15

-->      netbsd/386: github.com/hashicorp/vault

1 errors occurred:
--> netbsd/386 error: exit status 2
Stderr: # github.com/pkg/browser
../../go/pkg/mod/github.com/pkg/browser@v0.0.0-20210706143420-7d21f8c997e2/browser_unsupported.go:7:2: imported and not used: "os/exec"
```

Workaround is to perform a `go get github.com/pkg/browser@681adbf594b8` to override this indirect dependency (in this case within Vault), but ideally this should be addressed directly on the module that's importing `pkg/browser`.

**Comment by sfc-gh-jbahk** [comment]
Thank you for your concern. We've merged https://github.com/snowflakedb/gosnowflake/pull/508. Please find the updated version in the next release.
