### ISSUE TITLE
SNOW-516933: Scan still produces string when the destination is interface{} even after v1.6.0

### ISSUE THREAD

**Issue by YikSanChan** [snowflakedb/gosnowflake#513]
### Issue description

Scan produced string when the destination is interface{}, see https://github.com/snowflakedb/gosnowflake/issues/205

According to @sfc-gh-jbahk in https://github.com/snowflakedb/gosnowflake/issues/205#issuecomment-900526978, the issue has been resolved after v1.6.0, as gosnowflake uses arrow by default and the parsing logic has been fixed in arrow, see code https://github.com/snowflakedb/gosnowflake/blob/40a369edfdf64363fefb02a8df60f4e077d8f7da/converter.go#L319

However, I confirm that the issue is still there using v1.6.4.

### Example code

Modify [select1](https://github.com/snowflakedb/gosnowflake/blob/master/cmd/select1/select1.go), from

```go
var v int
	for rows.Next() {
		err := rows.Scan(&v)
		if err != nil {
			log.Fatalf("failed to get result. err: %v", err)
		}
		if v != 1 {
			log.Fatalf("failed to get 1. got: %v", v)
		}
	}
```

to

```go
var v interface{}
	for rows.Next() {
		err := rows.Scan(&v)
		if err != nil {
			log.Fatalf("failed to get result. err: %v", err)
		}
		fmt.Printf("%v(%T)\n", v, v)
	}
```

It prints

```
1(string)
Congrats! You have successfully run SELECT 1 with Snowflake DB!
```

### Configuration
*Driver version (or git SHA):* 1.6.4

*Go version:* 1.17.2

*Server version:* 5.43.1

*Client OS:* macOS 10.15.7

**Comment by sfc-gh-jbahk** [comment]
Hello @YikSanChan, this is because a select 1 query where you supply the expected result (as opposed to a normal query of the table) returns a JSON format result and thus a string within its interface. You are expected to get a typed variable if you use an interface{} with a regular query.
