### ISSUE TITLE
SNOW-524462: How can I use insert with prepared statement (without select statement) for VARIANT datatype?

### ISSUE THREAD

**Issue by aashakabra** [snowflakedb/gosnowflake#520]
### Issue description
I am trying to insert a json data ({"key": "value"})in variant column with prepared statement (without using select statement).

Below is the insert statement that I am trying to execute:
`insert into variantdata (ID, V) values (?, ?);`

what is the expected parameter to be set for parameter 2 i.e. so that I am able to insert above json data as variant column.

Note : 
When I use insert with select like below prepared statement, I am able to insert the column using the Go Snowflake driver 
```
query: insert into variantdata (ID, V) Select 1, parse_json(?);
parameters: {"newkey": "newvalue"}
```

### Example code
```go
If possible, please enter some example code here to reproduce the issue.
```

### Error log
```
If you have an error log, please paste it here.
```
Add ``glog` option to your application to collect log files.

### Configuration
*Driver version (or git SHA):*
SnowflakeGoDriverVersion = "1.2.0"

*Go version:* run `go version` in your console
1.14

*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```

*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10
MacOS, Windows 10, Linux

**Comment by sfc-gh-jbahk** [comment]
Hello @aashakabra, currently the Go driver does not support VARIANT binding. It is in the backlog but we are addressing some other priorities at the moment.
