### ISSUE TITLE
SNOW-526565: `ExecContext()` returns seemingly empty error: `-00001:`

### ISSUE THREAD

**Issue by colmsnowplow** [snowflakedb/gosnowflake#524]
### Issue description
Long-running DML statements occasionally return an error which seems to have an empty message, whereby the `error.Error()` provides only `-00001:`.

I've encountered this several times for two production jobs, but as yet haven't managed to reproduce locally (once I do I'll update here with more specifics).

This seems to occur for long-running statements that fail after ~90 minutes, which leads me to believe that a query timeout might sometimes be involved, however that scenario usually leads to this error:

`000630 (57014): Statement reached its statement or warehouse timeout of 5,400 second(s) and was canceled.`

What's more curious is that the customer reports that the Snowflake UI displays this query has having been successfully completed.

It is possible that something is going wrong with  parsing the error that this package returns, but I've dug through it and so far everything I can see points to the database or the driver genuinely returning only `-00001:`.

I hope someone can help me understand this - is it possible that Snowflake DB or this package returns this as an error? If so, could anyone provide some clues to explain what causes this?

### Example code
I will update here with code to reproduce once I manage to do so. In the meantime, it might be of interest to know that in the two separate jobs that have encountered this, the problematic queries are as follows:

```
CREATE TABLE IF NOT EXISTS myschema.mytable (
  ...

);


TRUNCATE TABLE myschema.mytable;

INSERT INTO myschema.mytable (

  WITH prep AS (

    SELECT event_id FROM scratch.ids GROUP BY 1

  )

  SELECT
    ...

  FROM myschama.fairly_large_table AS ev

  INNER JOIN prep AS id
    ON ev.event_id = id.event_id

  WHERE
    {{some conditions, which include limiting on a clustering key}}
);
```

Any help debugging this would be greatly appreciated.

**Comment by sfc-gh-jbahk** [comment]
Hi @colmsnowplow, thank you for opening this issue. We are looking into this. In the meantime, would you be able to provide any logs/query IDs as well as the version of the driver, etc any other relevant specs that would aid this investigation? Thanks.

**Comment by colmsnowplow** [comment]
Hi @sfc-gh-jbahk,

I can't get the query ID unfortunately as my app just submits to a job in the customer account which I don't have access to - I've asked them for it so if they provide it I'll pass it on. I have opened a ticket with Snowflake Support and based on what they told me it seems unlikely to be coming from the database. 

I encountered the issue on v1.4.3 - I've been unable to reproduce locally but am in the process of deploying the app with v1.6.5, to see if this resolves it. I didn't see anything in the diff between v1.4.3 and latest that looked likely to address it though.

Since opening this issue, I've noticed that [there is a circumstance where the driver can return just a response code of -1](https://github.com/snowflakedb/gosnowflake/blob/6ee2a7496810d8b1ca33f8d47f02a7403282e5f3/connection.go#L140-L157). I've also confirmed that the templater in my app will convert this error to `-00001:`. 

From my reading, this can get returned when the request to the database responds with no error but also no response code. So my efforts now are towards attempting to reproduce that circumstance - if I manage to do so I'll post the code here. :)

**Comment by colmsnowplow** [comment]
Hi @sfc-gh-jbahk ,

Having reflected on this issue, I'd like to try to articulate what I think would be most helpful for me at the moment. I'm not sure whether this is unexpected behaviour from the driver, or just expected behaviour that I don't fully understand. I'm hoping you might help me understand how to handle the case either way.

The code [explicitly handles](https://github.com/snowflakedb/gosnowflake/blob/6ee2a7496810d8b1ca33f8d47f02a7403282e5f3/connection.go#L140-L145) the case where the http request to the database responds without an error, but with an empty code. In this scenario it sets the code to `-1` and returns an error (which matches what I've encountered here).

What I'm still confused about is what scenario this is intended to cover. If the context is cancelled, the request times out, or network connection is lost, I would expect some error or another to be thrown. Same for session closure on the database side. 

Do you have any idea what scenario can produce a case where the request to the database returns with an empty code, but also no error?

**Comment by sfc-gh-jbahk** [comment]
Hi @colmsnowplow, thank you for bringing this up. Indeed I can't think of a specific instance off the top of my head where the data.Code is nil but also is recognized as a successful request - I would assume, yes, for an unsuccessful request to come with a specific error code of its own. 

The error thrown would be from the ensuing data.Success check, at which point all the relevant information (message, sqlstate, query ID) would also be returned to the user. Since the driver aims to be faithful in capturing the error information returned by the server side, I believe a remedy on the client (driver) side would be helpful in your case. However, without the ability to clearly reproduce this issue or see how this was caused, it doesn't seem very feasible to target those errors at the moment.

Would you have any suggestions here?

**Comment by sfc-gh-jbahk** [comment]
A hot fix that I can think of is pre-populate the fields that would be returned to the user with a generic error message/SQL state (as is done with the code) and replace them with the actual information returned by the server so you'd receive something other than just "-0001".

**Comment by colmsnowplow** [comment]
Thanks for the response @sfc-gh-jbahk.

I appreciate that without a repro it's hard to know where to take this, your input so far has been helpful in thinking through it and trying to reproduce. I could indeed replace the error with something more readable, however I'm more concerned with addressing the customers' pain, which is the fact that their sql jobs are failing. 

To that end, I've been trying to reproduce this and there are two things that might be interesting to you from that process.

1. ExecContext hangs on lost connection
Firstly, I wondered if a lost network connection might be at play here. It doesn't seem to be, but the results of that test are still unexpected behaviour. If we open a connection and make a query via `ExecContext()`, then while it's waiting for a response we lose network connection, `ExecContext()` will hang indefinitely.

I discovered this by running the below, and turning off Wifi after `executing query` is printed.

```
package main

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	sf "github.com/snowflakedb/gosnowflake"
)

func main() {
	configStr, err := sf.DSN(&sf.Config{
	...
	})

	script := "call system$wait(2, 'MINUTES')"

	db, err := sql.Open("snowflake", configStr)

	ctx, _ := sf.WithMultiStatement(context.Background(), 0)
	
	fmt.Println("executing query")
	res, err := db.ExecContext(ctx, script)
	fmt.Println("done executing query")

	fmt.Println("RES:", res)
	fmt.Println("ERR:", err)
}```

I left this running with Wifi off overnight, and over 12 hours later the script was still running. I'm not sure what intended behaviour would be in this (admittedly weird) circumstance, but I would've thought that a lost connection would return an error at some point.

That's just an FYI because it's the kind of thing I'd like someone to point out on a project that I work on - it doesn't actually affect me or cause issues for me.

When we restore connection, it does eventually return an error.


2. The only explanation for -1 error is an empty response
I've looked into our deployment, network, our app code, the driver code, and tested behaviour across different versions of the driver. I've ruled out everything I can think of, and I cannot reproduce this behaviour. The only circumstance I can see where it's possible to return `-1` from this driver is that the Snowflake Server genuinely returned an empty response. I might be wrong here, but we have seen much weirder quirky behaviour from all of the cloud service providers we work with (which is most of them), so it's not out of the bounds of possibility that we just have  encountered some rare weird behaviour.

Notable to this hypothesis is that we only see this for two of our customers, but we have many Snowflake customers - but we see it a few times a week for those customers (which is frequent enough that it seems not to be a coincidence).

---

My plan from here is to amend my app to retry when it gets this error, and also to grab the query ID and include it as part of any error we hit, if I can access the query ID from the client. If we encounter this issue again once that's deployed, hopefully we can follow up here or with the Support team with some actual query IDs.

I'd be very interested to hear anything you or the team discover or think of that might help me understand this better. For now I don't think it's possible for me to handle this in the app any better than just retrying.

I appreciate your and the rest of the team's help. :)

**Comment by colmsnowplow** [comment]
Actually I might be able to do one better than a retry - @sfc-gh-jbahk sorry to pester with a double-message - if I use [query status polling](https://github.com/snowflakedb/gosnowflake/pull/467) I assume that the result for a multi-statement query will include the results for all statements in the query?

If I can simply handle this exception by polling the database for a genuine result, we can gracefully recover - I'd be quite happy with that outcome. :)

**Comment by sfc-gh-jbahk** [comment]
@colmsnowplow  I think you may be correct in assuming that the error comes from the server side. As you point out, however, without a reproducible query (or iD), it is quite difficult to diagnose and pass the information to debug.

I believe the query status returned by the poll will only be applicable to the entirety of the query and not the individual subqueries (please correct me if I'm wrong @sfc-gh-cshi). Regardless, I think retroactively fetching the query result could provide some useful information, if not outright working!

**Comment by colmsnowplow** [comment]
Thanks, yes I've confirmed through some hacky tests that it behaves as I need it to, and one queryID/ call to `GetQueryStatus` covers the whole mutli-statement query. That's a nice feature, it allows me to mitigate this issue nicely.

I'll post some code here when I get a chance, before I close this issue, then as and when we can grab the query ID for a query that hits this issue, I'll send it through to the support team.

**Comment by colmsnowplow** [comment]
As promised, for anyone in the future who comes across the same scenario here's the solution I came up with to handle when we get this error:

```
// sft.Client is the sql.db client
	sfd := sft.Client.Driver()
	conn, err := sfd.Open(sft.Dsn)
	if err != nil {
		return errors.Wrap(err, "Failed to open connection to poll for query result.")
	}
	// Poll Snowflake for actual query status
	for {
		qStatus, err := conn.(sf.SnowflakeConnection).GetQueryStatus(context.Background(), queryId)

		switch {
		case err != nil && strings.Contains(err.Error(), "[RUNNING]"):
			// If there's an error, but it contains `[RUNNING]`, the query hasn't yet completed.
			break
		case err != nil:
			// Any other error is genuine, return the error.
			return err
		case qStatus != nil && qStatus.ErrorCode == 0:
			// A non-nil qStatus means the query completed. If the ErrorCode field is 0, we have no error.
			return nil
		case qStatus != nil:
			// If qStatus is non-nil but has a non-zero error code, return the relevant info as an error.
			return errors.New(qStatus.ErrorMessage)
		default:
			break
		}
		// Give it thirty seconds before polling again.
		time.Sleep(60 * time.Second)
	}
```

Closing this issue. Thanks again for your help reasoning through the issue @sfc-gh-jbahk. I've also added the queryID to all error messages (and also we print it when we hit this scenario), so once I have an example of this scenario I'll forward that on to the team so you folks can take a look at what might be happening server side.

**Comment by colmsnowplow** [comment]
👋  just a quick follow-up, the fix seems to have mitigated the issue, and I have shared some queryIDs for the Snowflake team's reference in support ticket number 00315432. :)

**Comment by sfc-gh-jbahk** [comment]
Thank you! @colmsnowplow we'll review it and see if there are changes we can make.
