### ISSUE TITLE
SNOW-534077: Panic on missing chunk-downloader for multi-statement response that is missing child request-IDs.

### ISSUE THREAD

**Issue by agam** [snowflakedb/gosnowflake#532]
### Issue description
Within `queryContextInternal`, when handling a multi-statement query (https://github.com/snowflakedb/gosnowflake/blob/941a4ebab564328880e80dfcebee7e4d2ddb1fbb/connection.go#L361-L364), we create a new `chunkDownloader` for each child-request (https://github.com/snowflakedb/gosnowflake/blob/941a4ebab564328880e80dfcebee7e4d2ddb1fbb/multistatement.go#L87-L98).

However, _if_ `ResultIDs` within `execResponseData` is an empty string, we will _not_ create _any_ `chunkDownloader` here, and later panic when trying to `start()` it.

For more context, here's the relevant portion (from `queryContextInternal` within `connection.go`):
```go
	if isMultiStmt(&data.Data) {
		// handleMultiQuery is responsible to fill rows with childResults
		if err = sc.handleMultiQuery(ctx, data.Data, rows); err != nil {
			return nil, err
		}
	} else {
		rows.addDownloader(populateChunkDownloader(ctx, sc, data.Data))
	}

	rows.ChunkDownloader.start()
```

I believe this condition (i.e. an empty `data.Data.ResultIDs` and a resulting `nil` value for `rows.ChunkDownloader`) is known within the `if isMultiStmt` block, and some error can be returned there.

**Comment by sfc-gh-jbahk** [comment]
Done.

**Comment by agam** [comment]
Thanks!
