### ISSUE TITLE
SNOW-546088: Breaking change in `patch` version `1.6.7`

### ISSUE THREAD

**Issue by stoffeastrom** [snowflakedb/gosnowflake#552]
### Issue description

Upgrading from `1.6.6` introduces a breaking change in

```go
gosnowflake.WithRequestID
```

This now uses an *internal* only uuid implementation

**Comment by sfc-gh-jbahk** [comment]
@stoffeastrom Thank you for bringing this up. We are aware of this and will look to mitigate the issue. May I ask how you're using this piece of code?

**Comment by stoffeastrom** [comment]
@sfc-gh-jbahk Thanks for your reply.

```golang
import "github.com/google/uuid"

requestID := uuid.New()
ctx = sf.WithRequestID(ctx, requestID)
```

this `requestID` is then logged in our system to be able to track current request.

**Comment by sfc-gh-jbahk** [comment]
I see. It was shortsighted to not include a proper notice and code that would be able to cater to usage like that. We are trying to veer way from third party APIs/SDKs that have broken in the past. Would it suit your case to have a method in which it can create a snowflake UUID?

**Comment by stoffeastrom** [comment]
Yes, that should be sufficient enough I think. I guess this stems from the rest api

<img width="1654" alt="image" src="https://user-images.githubusercontent.com/682243/155216021-7df3d434-57e8-47a9-bd13-34c1a3b7a647.png">

Totally get the veer away from third party apis argument..
