### ISSUE TITLE
SNOW-551325: Panic on missing Location in call to Time.In

### ISSUE THREAD

**Issue by jpmunz** [snowflakedb/gosnowflake#555]
### Issue description

Not sure if related to https://github.com/snowflakedb/gosnowflake/issues/550, in attempting to upgrade from 1.6.6 to 1.6.7 I started seeing a panic:

```
time: missing Location in call to Time.In
```

I believe as a result of this change:
https://github.com/snowflakedb/gosnowflake/compare/v1.6.6...v1.6.7#diff-ecad48054a05ca5aecf42b278530331772747ed7211a193aacd94214cb53aad0R227

**Comment by sfc-gh-jbahk** [comment]
Hi @jpmunz could you share the code that caused this error? Thanks.

**Comment by kpruden** [comment]
I don't have an easy repro, but the panic I'm getting points to this line of code:

https://github.com/snowflakedb/gosnowflake/blob/master/converter.go#L227

**Comment by jmrobles** [comment]
I think is related with https://github.com/snowflakedb/gosnowflake/issues/565

**Comment by sfc-gh-dszmolka** [comment]
should be resolved by #571
