### ISSUE TITLE
SNOW-551650: Is the parameter cfg.`KeepSessionALive` useless in HeartBeat?

### ISSUE THREAD

**Issue by kchojn** [snowflakedb/gosnowflake#556]
### Issue description
I was wondering why I keep getting the message `Authentication token has expired`, even if I've set `KeepSessionAlive` as `True` in the config.
Analyzing the code, I see that it is not parsed and used anywhere. The `keep session alive` parameter is taken from `Params`. Also I see that heartBeat is based on `params`:
Edit: I'm using dsn 
```go
func (sc *snowflakeConn) isClientSessionKeepAliveEnabled() bool {
	v, ok := sc.cfg.Params[sessionClientSessionKeepAlive]
	if !ok {
		return false
	}
	return strings.Compare(*v, "true") == 0
}
```
Should I only use params for additional settings then?

### Example code
```go
func getDSN() (string, *sf.Config, error) {
	cfg := &sf.Config{
		Account:          setting.DatabaseSetting.Account,
		User:             setting.DatabaseSetting.User,
		Password:         setting.DatabaseSetting.Password,
		Database:         setting.DatabaseSetting.Database,
		Schema:           setting.DatabaseSetting.Schema,
		Warehouse:        setting.DatabaseSetting.Warehouse,
		Role:             setting.DatabaseSetting.Role,
		Region:           setting.DatabaseSetting.Region,
		KeepSessionAlive: true,
	}
	dsn, err := sf.DSN(cfg)
	return dsn, cfg, err
}
```

### Error log
```sh
time="2022-02-24T07:28:45Z" level=error msg="error: 390114: Authentication token has expired.  The user must authenticate again." func="gosnowflake.(*snowflakeConn).queryContextInternal" file="connection.go:338"
```

### Configuration
*Driver version (or git SHA):* latest

*Go version:*  go1.17.6 linux/amd64

*Server version:* 6.4.1

*Client OS:* <pre>Ubuntu 18.04.6 LTS</pre>

**Comment by kchojn** [comment]
Looks like `client keep seesion alive` param is not working either
```go
params["client_keep_session_alive"] = clientKeepSessionAlive
```

4 hours later:
```sh
time="2022-02-24T14:09:09Z" level=error msg="error: 390114: Authentication token has expired.  The user must authenticate again." func="gosnowflake.(*snowflakeConn).queryContextInternal" file="connection.go:338"
```

I also do not see the execution of `select 1` in the history panel. Only after running.

This is how db is created:
```go
func Setup() {
	dsn, _, err := getDSN()
	if err != nil {
		log.Fatal(err)
	}
	db, err := sql.Open("snowflake", dsn)
	if err != nil {
		log.Fatalf("SnowFlake setup err: %v", err)
	}

	err = db.Ping()
	if err != nil {
		log.Fatalf("SnowFlake ping err: %v", err)
	}

	db.SetMaxIdleConns(10)
	db.SetMaxOpenConns(100)

	Db = db
}
```

**Comment by sfc-gh-wfateem** [comment]
Hi @kchojn,
I think you might have swapped parts of the name, it should be client_session_keep_alive not client_keep_session_alive, and you can set that in the DSN.

**Comment by kchojn** [comment]
Hey @sfc-gh-wfateem ,
Thank you for your time and response. I agree, I made a mistake 😳 It seems to be working now!

What about config attr `KeepSessionAlive`? Does it have any use?

**Comment by sfc-gh-wfateem** [comment]
Hey @kchojn,

I think what we're interested in is sessionClientSessionKeepAlive, but I do agree, KeepSessionAlive doesn't look like it has much use after skimming through the code briefly. Not sure what the history is behind that portion of the code. I'll look into it a bit and ask someone else who's a bit more familiar with this codebase in case there's some cleanup that needs to happen.
Concerning your issue though, are you good with using the option provided (client_session_keep_alive)?

**Comment by kchojn** [comment]
@sfc-gh-wfateem, yes, I'm good with that! Thank you. This config attr `KeepSessionAlive` was misleading, for me.
I will open pr with the usage of this parameter.
From my side everything is clear, feel free to close the issue if you want.

Regards!

**Comment by sfc-gh-wfateem** [comment]
All right then, thanks for reaching out @kchojn! Have a good one!
