### ISSUE TITLE
SNOW-563221: Crashed when locales files not found

### ISSUE THREAD

**Issue by jmrobles** [snowflakedb/gosnowflake#565]
### Issue description

During the session parameters initialization, there is no checking for error in `time.LoadLocation`
![image](https://user-images.githubusercontent.com/1277154/159680242-da221b89-3a0a-4077-9f9a-436809458928.png)

If `gosnowflake`runs in a container, probably the image can not include the timezone/locales files. 

It's necessary to check for the error and not ignore it.

### Example code

N/A

### Error log

Crashed when the `localLocation` is used (convert.go) during the app execution.

`panic: tiime: missing Location in call to Time.In`

### Configuration
*Driver version (or git SHA):* v1.6.7

*Go version:* 1.18

*Server version:* 6.8.1

*Client OS:* Ubuntu 20.04

**Comment by sfc-gh-dszmolka** [comment]
should be resolved with #571
