### ISSUE TITLE
SNOW-583475: How to insert DataTypeObject ?

### ISSUE THREAD

**Issue by AlmogBaku** [snowflakedb/gosnowflake#576]
How do I inset a DataTypeObject? should I create a struct? should I marshal to json?
An example would be helpful :)

Thanks

**Comment by AlmogBaku** [comment]
for anyone interested, I solved it by serializing my object to *JSON string* - then deserializing it in the SQL query: via `parse_json(?)`

**Comment by gangtao** [comment]
Yes, is there a sample for this? I dont think the parse_json solve this problem?

**Comment by sfc-gh-dszmolka** [comment]
if this is still an issue - could you please provide an example of what you're trying to do, and what are the obstacles; why `parse_json` is not good enough for your case ? thank you in advance !
