### ISSUE TITLE
SNOW-585196: Snowflake UI shows parameterized sql instead of complete sql

### ISSUE THREAD

**Issue by kishvanchee** [snowflakedb/gosnowflake#577]
### Issue description
I expect to see the actual query being recorded in the snowflake UI. Instead I am seeing parameterized sql.

What I expect
```sql
SELECT column_name, data_type FROM customer_platform.information_schema.columns WHERE table_name = 'EXAMPLE_TABLE'
```

What I see
```sql
SELECT column_name, data_type FROM customer_platform.information_schema.columns WHERE table_name = ?
```
![Screenshot_20220504_032056](https://user-images.githubusercontent.com/24776049/169072035-22e30b4d-c4bc-4ccd-97c6-3afaf5140429.png)

### Example code
```go
// pretty std code
sql = "SELECT column_name, data_type FROM customer_platform.information_schema.columns WHERE table_name = ?"
args = []interface{}{"EXAMPLE_TABLE"}
rows, err := db.Query(sql, args...)
```

### Configuration
*Driver version (or git SHA):* v1.6.9

*Go version:* go version go1.18.1 linux/amd64

*Server version:* 6.14.0

*Client OS:* Arch Linux

**Comment by sfc-gh-dszmolka** [comment]
thank you for raising this issue with us ! this is the current intended behaviour on the server-side, independently from the client library used.

if you need to keep track of the parameters, perhaps you can log them on the client side before issuing the query to snowflake (or even insert them into a separate snowflake table )
