### ISSUE TITLE
DisableTelemetry is ignored

### ISSUE THREAD

**Issue by Thomasdezeeuw** [snowflakedb/gosnowflake#613]
Just looking through the code it's quite obvious.

First there is a check that set a disabled telementry client:

https://github.com/snowflakedb/gosnowflake/blob/3c7253cb065fc33771a2e9b46c5ae8c00f321fdd/connection.go#L448-L450

However it's overwritten a couple of lines later:

https://github.com/snowflakedb/gosnowflake/blob/3c7253cb065fc33771a2e9b46c5ae8c00f321fdd/connection.go#L477-L482

**Comment by Thomasdezeeuw** [comment]
Seems that the JIRA setup is also failing: https://github.com/snowflakedb/gosnowflake/runs/7197178476?check_suite_focus=true.

**Comment by sfc-gh-dszmolka** [comment]
hi @Thomasdezeeuw - thanks for drawing our attention to this issue, we'll look into it. Also appreciate the notification about the failing github action, we'll check that too (and why this issue was auto-closed).

**Comment by sfc-gh-dszmolka** [comment]
sadly i don't have such privileges, i would have done it if i could. but we're looking into it at the following (manually opened :| ) internal tickets:
SNOW-623421 - [gosnowflake] DisableTelemetry is ignored
SNOW-623405 - [gosnowflake] Github Action create-jira is failing

can update you here on the progress (or you can watch the PR's yourself for the first one, I suppose there should one one sooner or later, addressing the issue)
