### ISSUE TITLE
SNOW-636038: Is "application" Connection Parameter in Snowflake GoDriver same as "application" Connection Parameter in Snowflake JDBC driver

### ISSUE THREAD

**Issue by aashakabra** [snowflakedb/gosnowflake#628]
In case of JDBC driver- https://docs.snowflake.com/en/user-guide/jdbc-parameters.html#other-parameters
Connection parameter '**application**' can be used and on above link it has the description as '**Snowflake partner use only: Specifies the name of a partner application to connect through JDBC.**'

I am looking for similar implementation to be done using GoDriver.
On this page - https://pkg.go.dev/github.com/snowflakedb/gosnowflake#hdr-Connection_Parameters there is a mention of below content for '**application**' parameter-
'**application: Identifies your application to Snowflake Support.**'

Does this parameter in GoDriver has the same purpose as mentioned in JDBC driver?

If not, then what connection parameter in GoDriver can be used for Snowflake partner application name while connecting to Snowflake?

**Comment by sfc-gh-jbahk** [comment]
Hi, yes it is the same as the JDBC driver.
