### ISSUE TITLE
SNOW-645253: Named bind parameters in exec fails

### ISSUE THREAD

**Issue by tayknight** [snowflakedb/gosnowflake#644]
_go version_
go version go1.19 windows/amd64

_go mod_
go 1.19
github.com/snowflakedb/gosnowflake v1.6.12

_Server version_
6.27.0

### Issue description
When trying to use a named bind variable in an db.Exec statement an error is retuned.

`sf_result, err := snowflake_db.Exec("INSERT INTO DA_DW_DEV.STG.CV_TLMSD_API_TERMS (ID) VALUES (:id)", sql.Named("id", "1"))`

```
002049 (42601): SQL compilation error: error line 1 at position 58
Bind variable :id not set.
```

A "normal" question-mark bind works fine...
`sf_result, err := snowflake_db.Exec("INSERT INTO DA_DW_DEV.STG.CV_TLMSD_API_TERMS (ID) VALUES (?)", "1")`

RowsAffected() returns 1 row.

Thanks for any advice or help.

**Comment by anekdoti** [comment]
I have the same problem with gosnowflake v1.6.13. Executing the statement `db.Exec("CREATE SCHEMA IDENTIFIER(:FOO)", sql.Named("FOO", "MYSCHEMA"))` yields the error

**Comment by sfc-gh-dszmolka** [comment]
thank you for submitting this issue, it is indeed reproducible even with the latest version of the `gosnowflake` driver, `v1.6.19`. we'll take a look to see how this issue can be addressed. In the meantime, the `?` or even the positional `:1` (`:2`, `:3` etc) binding can be used as a workaround.

**Comment by sfc-gh-dszmolka** [comment]
#850

**Comment by sfc-gh-dszmolka** [comment]
PR is merged and will be part of the next upcoming release, expected towards end of July

**Comment by sfc-gh-dszmolka** [comment]
version 1.6.23 of the driver has been released with the fix
