### ISSUE TITLE
SNOW-657330: WithFileStream support for GET queries

### ISSUE THREAD

**Issue by mihaitodor** [snowflakedb/gosnowflake#654]
### Issue description
I'd like to write some code which downloads a file from a Snowflake stage into an in-memory stream. However, it looks like this client library [only supports](https://pkg.go.dev/github.com/snowflakedb/gosnowflake#hdr-Using_GET) specifying an actual file as the destination. Note that for PUT operations, I can use [`WithFileStream`](https://pkg.go.dev/github.com/snowflakedb/gosnowflake#WithFileStream) to do the reverse operation.

### Example code

See the documentation [here](https://pkg.go.dev/github.com/snowflakedb/gosnowflake#hdr-Using_PUT) and [here](https://pkg.go.dev/github.com/snowflakedb/gosnowflake#hdr-Using_GET) and the code [here](https://github.com/snowflakedb/gosnowflake/blob/5da2ab2463b2c7e544722bc58defdb23397287d6/connection_util.go#L84-L89) which only applies to PUT operations.

### Error log

N/A

### Configuration

N/A

**Comment by sfc-gh-dszmolka** [comment]
thank you for raising this request with us, we'll see how this capability could be added to the driver. cannot commit to any expected timeline - thank you for bearing with us !

**Comment by mihaitodor** [comment]
Are there any updates on your roadmap regarding this enhancement? It would be great to be able to add a `GET`-based input to [Benthos](https://benthos.dev), since right now it only provides a `PUT`-based output.

**Comment by sfc-gh-pfus** [comment]
Hi @mihaitodor ! We are in the process of planning upcoming three months. I added this one as a candidate. Fingers crossed it will be accepted to do!

**Comment by sfc-gh-dszmolka** [comment]
we now have a draft PR at https://github.com/snowflakedb/gosnowflake/pull/1192 for the implementation. will keep this thread posted.

**Comment by sfc-gh-dszmolka** [comment]
change has been merged and will be part of the next release, expected coming in the near future

**Comment by sfc-gh-dszmolka** [comment]
released with gosnowflake v.1.11.1
