### ISSUE TITLE
SNOW-681265: Feature request: Support PUT from memory stream (io.Reader)

### ISSUE THREAD

**Issue by fsaintjacques** [snowflakedb/gosnowflake#675]
### Issue description
I find the `PUT file://` to be restrictive. We run our services in kubernetes on diskless nodes. The fact that we need local disks (we can cheat and use tmpfs and/or mkfifo, but it still needs to roundtrip via the kernel) is a bummer. I would really like that PUT supports in memory `io.Reader` that avoid disk materialization.

### Example code
```go

var r io.Reader = ...
// Registers the reader in a global map
gosnoflake.PutRegisterReader("a-unique-key", r)
// Reads data from `r` instead of local disk
db.Exec("PUT mem://a-unique-key/ ..."
```

**Comment by fsaintjacques** [comment]
BigQuery has no issue doing this https://github.com/googleapis/google-cloud-go/blob/bigquery/v1.42.0/bigquery/file.go#L23-L39

**Comment by fsaintjacques** [comment]
I'll close this since it's possible via `WithFileStream`.

**Comment by fsaintjacques** [comment]
Actually, I'm going to leave this open. While the library does indeed support an io.Reader, it streams everything to memory https://github.com/snowflakedb/gosnowflake/blob/master/connection_util.go#L113

**Comment by sfc-gh-dszmolka** [comment]
hi, thank you for raising this request with us. as you mentioned, `WithFileStream` can be used in `PUT` operations (https://pkg.go.dev/github.com/snowflakedb/gosnowflake#hdr-Using_PUT)

would that not fit the purposes of not needing to use disk to `PUT` files ?

**Comment by sfc-gh-dszmolka** [comment]
closing this one as it's been inactive for a month.
