### ISSUE TITLE
SNOW-693854:  Track upgrade of go-ieproxy

### ISSUE THREAD

**Issue by sfc-gh-ext-simba-lb** [snowflakedb/gosnowflake#690]
### Issue description
Creating this issue to track the upgrade of go-ieproxy library. The upgrade is blocked until https://github.com/mattn/go-ieproxy/issues/45 is resolved.

### Example code
```go
N/A
```

### Error log
```
N/A
```
Add ``glog` option to your application to collect log files.

### Configuration
*Driver version (or git SHA):* v 1.6.14

*Go version:* run `go version` in your console

*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```

*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10

**Comment by sfc-gh-dszmolka** [comment]
https://github.com/mattn/go-ieproxy/issues/45 is fixed now since ~5 days
