### ISSUE TITLE
Implement PUT and GET

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/gosnowflake#7]
### Issue description
PUT and GET support. This requires AWS SDK to communicate with S3.

**Comment by smtakeda** [comment]
This is not for v1.0

**Comment by tjj5036** [comment]
If no one has started work on this I'd be happy to do it.

**Comment by smtakeda** [comment]
@tjj5036 great! See python connector about how it works. Let me know if you have questions. Thanks!

**Comment by tjj5036** [comment]
I've started working on PUT support, currently working off https://github.com/tjj5036/gosnowflake/tree/put_and_get

**Comment by kheraankit** [comment]
Do we know what release version this will be available?  We have several usecases waiting on this feature.

**Comment by smtakeda** [comment]
Not in the short team plan. Can you please reach out the customer support or SE to raise the request?

**Comment by sfc-gh-jbahk** [comment]
PUT for AWS S3 is supported as per v1.4.3; Azure/GCS per the next release, v1.5.1

**Comment by sfc-gh-jbahk** [comment]
Closing this as GET also supported as per v1.6.1.
