### ISSUE TITLE
SNOW-747364: Why are dependencies vendored?

### ISSUE THREAD

**Issue by judahrand** [snowflakedb/gosnowflake#729]
### Issue description
What is the rationale for vendoring dependencies? 

Can we move away from vendored dependencies so that this driver can be more easily used in other projects?

**Comment by judahrand** [comment]
@sfc-gh-ext-simba-lb ?

**Comment by sfc-gh-dszmolka** [comment]
thank you for opening this request ! we'll consider it - can't promise any timeline though when it will be picked up, so thank you for bearing with us !

**Comment by sfc-gh-dszmolka** [comment]
#776 merged into main
