### ISSUE TITLE
SNOW-780614: GoSnowflake not always respecting context deadline exceeded

### ISSUE THREAD

**Issue by grindlemire** [snowflakedb/gosnowflake#767]
1. What version of GO driver are you using?
`v1.6.17`
   
2. What operating system and processor architecture are you using?
Running in aws lambda
   
3. What version of GO are you using?
`v1.19`

4. Server version:* E.g. 1.90.1
Not important here

5. What did you do?
We are trying to chase down occasional timeouts we are seeing where requests are apparently getting stuck while running a QueryContext and paging through the returned rows. We have been unable to consistently reproduce it though. It is apparent though that something within gosnowflake is not respecting the deadline in the provided context passed in.

Reading through the code it does look like the retry code for the `snowflakeChunkDownloader` is not respecting context deadlines like other places in the code but perhaps there is a reason it is not being respected there? I put a [PR](https://github.com/snowflakedb/gosnowflake/pull/766) in case it was for your review.

6. What did you expect to see?
 I expect gosnowflake to return early if the passed in context is cancelled or times out.

**Comment by grindlemire** [comment]
#766 is the PR related to this issue.

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this issue with us and especially for already suggesting a possible PR ! we'll take a look.

**Comment by sfc-gh-dszmolka** [comment]
fix released with version [1.6.21](https://github.com/snowflakedb/gosnowflake/releases/tag/v1.6.21), closing this issue
