### ISSUE TITLE
Zombie dbus processes generated by github.com/99designs/keyring

### ISSUE THREAD

**Issue by mihaitodor** [snowflakedb/gosnowflake#773]
I noticed that `gosnowflake` added https://github.com/99designs/keyring as a dependency and, unfortunately, this library has an [outstanding bug](https://github.com/99designs/keyring/issues/103) which can lead some Linux systems to create zombie dbus processes. This issue was observed initially when importing the Apache Pulsar client library into Benthos as described [here](https://github.com/benthosdev/benthos/issues/1184) and it's triggered in one of the `init()` functions from `github.com/99designs/keyring`. One workaround that I identified is to set `DBUS_SESSION_BUS_ADDRESS=/dev/null` on process startup.

I tried to reproduce it in a Docker container, but didn't succeed yet, so I opened this issue to raise awareness and I'll share detailed reproduction steps at a later time if I get more time to poke around with it.

**Comment by sfc-gh-dszmolka** [comment]
hi @mihaitodor (or anyone else stumbling into this issue) - first of all, thank you so much for raising this with us and for providing the details about the issue and even the workaround to tackle it. This is highly appreciated.

I would recommend marking this as closed until a reproduction is available. The issue can be still commented to, even in Closed state, and I can reopen it when it becomes more actionable with the repro. Thank you in advance !

**Comment by crflanigan** [comment]
This issue appears to still exist:
https://github.com/influxdata/telegraf/issues/13481

**Comment by sfc-gh-dszmolka** [comment]
hi folks - I see sometimes people stumble into this issue; so apparently it's still here. We're taking a look.

**Comment by mihaitodor** [comment]
It hasn't been resolved, unfortunately... We're forcing a fork of `github.com/99designs/keyring` in Benthos: https://github.com/benthosdev/benthos/blob/bde063a467bd5e783c525365cb13ac239c0eb4e5/go.mod#L3, but that breaks `go install`, which is quite annoying:

```shell
> go install github.com/benthosdev/benthos/v4/cmd/benthos@latest
go: downloading github.com/benthosdev/benthos/v4 v4.20.0
go: github.com/benthosdev/benthos/v4/cmd/benthos@latest (in github.com/benthosdev/benthos/v4@v4.20.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

Related issues:
- https://github.com/99designs/keyring/issues/103
- https://github.com/apache/pulsar-client-go/issues/836
- https://github.com/benthosdev/benthos/issues/1184

It would be amazing if https://github.com/99designs/keyring addresses this issue, but I think the best bet is for both `gosnowflake` and `pulsar-client-go` to consider replacing it with a maintained fork. That will solve the issue for downstream projects.

**Comment by sfc-gh-dszmolka** [comment]
thank you so much for the summary and sharing your approach @mihaitodor  !
at least now I finally found a way how to reproduce the issue: on a RHEL 7.9 Maipo VM, using go1.21.0, simply running the example [select1.go](https://github.com/snowflakedb/gosnowflake/blob/master/cmd/select1/select1.go) produces an instance of 
```
/usr/bin/dbus-daemon --fork --print-pid 4 --print-address 6 --session
```

Each rerun of the script produces one instance of the `dbus-daemon` process just exactly as mentioned on https://github.com/hashicorp/vault/issues/22560. (i'm missing the `--syslog` argument but I think that's irrelevant for this issue)

hopefully this allows us to address it faster.

**Comment by aphorise** [comment]
This issue also occurs on Vault 1.13.7 that's also making use of this Dbus package.

**Comment by crobert-1** [comment]
I filed an issue as well, not knowing this was already raised against this repository: https://github.com/99designs/keyring/issues/135

The Snowflake receiver in the OpenTelemetry Collector is importing this repo, and thus causing a leaked goroutine there. Shown in PR description [here.](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30492)

**Comment by sfc-gh-dszmolka** [comment]
aforementioned change has been merged, and will be part of the next driver release cycle towards end of March.

**Comment by sfc-gh-dszmolka** [comment]
fix released with 2024 March release, version 1.9.0

**Comment by AS-auxmoney** [comment]
@sfc-gh-dszmolka 
We have encountered a similar problem this week **after** the update to `github.com/snowflakedb/gosnowflake v1.9.0`. Using the `v1.8.0` version we don't see this warning:
```
log.go:228 gosnowflake.(*defaultLogger).Warn DBUS_SESSION_BUS_ADDRESS envvar looks to be not set, this can lead to runaway dbus-daemon processes. To avoid this, set envvar DBUS_SESSION_BUS_ADDRESS=$XDG_RUNTIME_DIR/bus (if it exists) or DBUS_SESSION_BUS_ADDRESS=/dev/null.
```

**Comment by papajuan** [comment]
Hi guys! just letting you know that I repeated the issue on 
`debian:bookworm-slim`
with go version 1.25.1
There is a constant grow in memory (so each query processed via the Snowflake driver allocates more memory which is never released).
