### ISSUE TITLE
snowflakeTx needs to use the context object supplied by BeginTx(), not the context on the parent connection object

### ISSUE THREAD

**Issue by rohantandon** [snowflakedb/gosnowflake#796]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of GO driver are you using?

1.6.17
   
2. What operating system and processor architecture are you using?

mac OS Ventura 13.3.1 (a) x86_64
   
3. What version of GO are you using?
go version go1.20.4 darwin/amd64

4. Server version: 7.17.0

5. What did you do?

* Establish a connection to snowflake using PingContext(ctx) where the context is set with a short Deadline (say 3 seconds)
* Begin a transaction using BeginTx(ctx, opts) using a separate context object without a deadline
* Run a transaction that could potentially take more than 3 seconds
* Wait for transaction to commit or rollback.

6. What did you expect to see?

   The transaction executing successfully with a Commit() or failing with a Rollback()
   
   What should have happened and what happened instead?
   
   The transaction never commits or rolls back. Instead, the transaction gets stuck in holding state, and the server returns an error: `000605: Identified SQL statement is not currently executing

7. Can you set logging to DEBUG and collect the logs?

   https://community.snowflake.com/s/article/How-to-generate-log-file-on-Snowflake-connectors
   
8. What is your Snowflake account identifier, if any? (Optional)

---
This issue really stems from the fact that `Commit()` and `Rollback()` are not honoring the context supplied with `BeginTx(ctx)` - they are using a context supplied during PingContext(ctx) that gets stored in the parent `snowflakeConn` object.

So while BeginTx() uses one user-supplied context: https://github.com/snowflakedb/gosnowflake/blob/61ad7b87c8f94489df2ef848a91d8c37f43be00e/connection.go#L167-L194

The returned Transaction object doesn't obtain this context. Instead it uses the context from the parent connection:
https://github.com/snowflakedb/gosnowflake/blob/61ad7b87c8f94489df2ef848a91d8c37f43be00e/transaction.go#L9-L35

This means that `BEGIN` is executed using one context, whereas `COMMIT` and `ROLLBACK` are executed using a different one. If the context supplied in `PingContext(ctx)` has a short deadline, a transaction can get orphaned because it starts, but `COMMIT` and/or `ROLLBACK` fail because the context they're using has past its deadline.

This should be a straightforward change - pass the same context from BeginTx(ctx, opts) through to `snowflakeTx{}` and have all methods there use that context instead.

**Comment by sfc-gh-sghosh** [comment]
Hello @sfc-gh-ext-simba-lb (Lorna)

Could you please look into it?

Regards,
Sujan

**Comment by sfc-gh-fwang** [comment]
HI Team

Just wondering if there is any update?

Regards

**Comment by rohantandon** [comment]
Just adding a follow up here since there are other parts of the package that use this pattern. Storing context objects in a struct is a [go anti-pattern](https://go.dev/blog/context-and-structs). However, since the `database/sql` `Tx` interface doesn't support passing context objects via the `Commit()` and `Rollback()` methods, the context will need to be stored, but just for the duration of the transaction, and using the value supplied by `BeginTx(ctx, opts)`. This ensures that a single context is used for a single transaction

There are still other parts of the code base that are using this pattern, which can result in unpredictable behavior. For example, 

https://github.com/snowflakedb/gosnowflake/blob/72fecc7dc8c00851a1267159dacb0346cbbf0d68/file_transfer_agent.go#L541

is used by a method called by the `execute()` method:

https://github.com/snowflakedb/gosnowflake/blob/72fecc7dc8c00851a1267159dacb0346cbbf0d68/file_transfer_agent.go#L130

This in turn gets invoked by `processFileTransfer()`:

https://github.com/snowflakedb/gosnowflake/blob/72fecc7dc8c00851a1267159dacb0346cbbf0d68/connection_util.go#L78-L110

Where you end up having 2 separate contexts handling this operation: one supplied as an argument, and one stored in the connection object.

@fyi @grindlemire

**Comment by rohantandon** [comment]
> @rohantandon Could you provide the code to reproduce the exception?

Here you go. Replace the top variables with your credentials.

```go

package main

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"github.com/snowflakedb/gosnowflake"
	"log"
	"time"
)

var (
	myUser     = "<MY USERNAME>"
	myPassword = "<MY PASSWORD>"
	myHost     = "<MY ACCOUNT.snowflakecomputing.com>"
	myAccount  = "<MY ACCOUNT>"
)

func main() {

	cfg := gosnowflake.Config{
		User:          myUser,
		Password:      myPassword,
		Host:          myHost,
		Account:       myAccount,
		Authenticator: gosnowflake.AuthTypeSnowflake,
		Port:          443,
		Params:        make(map[string]*string), // This is potentially another bug, we shouldn't have to instantiate an empty map
	}

	connector := gosnowflake.NewConnector(gosnowflake.SnowflakeDriver{}, cfg)
	db := sql.OpenDB(connector)

	// Create a context with a deadline of only 3 seconds. This is because we want to fail fast if Ping doesn't return quickly
	ctx1, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	// ctx2 without a timeout for a long-running transaction
	ctx2 := context.Background()

	pingWithRetry := withRetry(PingFunc, 5, 3*time.Second)

	err := pingWithRetry(ctx1, db)
	if err != nil {
		log.Fatal(err)
	}

	tx, err := db.BeginTx(ctx2, nil)
	if err != nil {
		log.Fatal(err)
	}

	// This should be a no-op in case of a success
	defer tx.Rollback()

	_, err = tx.ExecContext(ctx2, "SELECT SYSTEM$WAIT(10, 'SECONDS')")
	if err != nil {
		log.Fatal(err)
	}

	err = tx.Commit()
	if err != nil {
		log.Fatal(err)
	}

	defer db.Close()
}

func PingFunc(ctx context.Context, db *sql.DB) error {
	return db.PingContext(ctx)
}

func withRetry(fn func(context.Context, *sql.DB) error, numAttempts int, timeout time.Duration) func(context.Context, *sql.DB) error {
	return func(ctx context.Context, db *sql.DB) error {
		for currAttempt := 1; currAttempt <= numAttempts; currAttempt++ {
			ctx, cancel := context.WithTimeout(ctx, timeout)
			defer cancel()
			err := fn(ctx, db)
			if err != nil {
				if errors.Is(err, context.DeadlineExceeded) {
					continue
				}
				return err
			}
			return nil
		}
		return fmt.Errorf("context deadline exceeded, failed after [%d] attempts", numAttempts)
	}
}

```

If you want to see the stack trace, try placing a break point at `connections.go` at line 34 and you'll see where the context is getting passed and stored:
```
gosnowflake.Connector.Connect (connector.go:34) github.com/snowflakedb/gosnowflake
<autogenerated>:2
sql.(*DB).conn (sql.go:1387) database/sql
sql.(*DB).PingContext.func1 (sql.go:850) database/sql
sql.(*DB).retry (sql.go:1538) database/sql
sql.(*DB).PingContext (sql.go:849) database/sql
main.PingFunc (main.go:71) main
main.withRetry.func1 (main.go:79) main
main.main (main.go:44) main
runtime.main (proc.go:250) runtime
runtime.goexit (asm_amd64.s:1598) runtime
 - Async Stack Trace
<autogenerated>:2
```
