### ISSUE TITLE
Concurrency issue with temporary tables

### ISSUE THREAD

**Issue by Tang8330** [snowflakedb/gosnowflake#805]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of GO driver are you using?
`v1.6.13`

3. What operating system and processor architecture are you using?
Linux AMD
   
4. What version of GO are you using?
run `go version` in your console
`go 1.16`

5.Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```
6. What did you do?

I am doing the following:
* Initializing the SQL driver and injecting this into `context.Context`
* Spawning N number of go-routines which consume from N number of Kafka topics
* Another process will periodically invoke MERGE and each MERGE will spawn go-routines that:
   1. Creates temporary tables
   2. Loads them
   3. MERGEs
   4. Deletes

I was finding myself having random concurrency issues where it would non-deterministically say the temporary table does not exist. That is when I stumbled upon this comment from 2018 https://github.com/snowflakedb/gosnowflake/issues/181#issuecomment-411904223. I have since specified this and the issue went away.

My question - is there a better way to deal with this? This will throttle my throughput. Also, just curious - why doesn't Snowflake support table expiration like BigQuery?

_N = number of tables_.

**Comment by sfc-gh-dszmolka** [comment]
Hi and thank you for raising this issue, also for linking the possible workaround here so others could also find if they bump into the same situation.

Do you think there's a chance for you to provide a minimal working code snippet, which when run, can lead to the reproduction of the issue ? It would immensely help the debug and bugfix procedure. Thank you in advance !

**Comment by Tang8330** [comment]
Hey @sfc-gh-dszmolka 

Hm, providing a snippet may be tricky because it's a concurrency problem.

To reproduce this, try these steps.

1. Create a couple of temporary tables
2. Spin up multiple go-routines and try to interact with tables created from (1)
3. As soon as it uses another connection from the pool, (2) will error out since tables from (1) will cease to exist.

**Comment by sfc-gh-dszmolka** [comment]
thank you for the details here, we're going to take a look.

**Comment by sfc-gh-pfus** [comment]
Hi @Tang8330 ! Does the problem still exist in the current driver version? Maybe it was solved by https://github.com/snowflakedb/gosnowflake/pull/897 ?

**Comment by sfc-gh-dszmolka** [comment]
since there's no response for a while, I'm now going to mark this one as closed for now. If it's still an issue, please feel free to comment with the details and we can reopen.
