### ISSUE TITLE
Bump up Arrow dependency to 12.0.1 to fix 32bit builds

### ISSUE THREAD

**Issue by burningalchemist** [snowflakedb/gosnowflake#822]
### Issue description
As the gosnowflake driver depends on the Apache Arrow dependency, there is a bug in **v12.0.0** which prevents compiling for 32bit systems (like linux/armv7) with the following error:

```
cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in assignment (overflows)
```

The issue has been confirmed and was fixed in **v12.0.1**. We currently can't use the latest available version (that also contains security fixes) due to the aforementioned error (it works fine on v1.6.18).

Ref: https://github.com/apache/arrow/pull/35767

### Configuration
*Driver version (or git SHA):* 1.6.19+
*Go version:* 1.20.4

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you so much for bringing this to our attention and raising the Issue ! we'll take a look.

**Comment by sfc-gh-dszmolka** [comment]
#829

**Comment by sfc-gh-dszmolka** [comment]
PR is merged and will be part of the next release

**Comment by sfc-gh-dszmolka** [comment]
version 1.6.23 of the driver has been released with the fix
