### ISSUE TITLE
Bug: populateSessionParameters call panics with `assignment to entry in nil map` message

### ISSUE THREAD

**Issue by davidhcoe** [snowflakedb/gosnowflake#826]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of GO driver are you using?

1.6.23 (master)
   
2. What operating system and processor architecture are you using?

Windows 11,  AMD64

3. What version of GO are you using?
run `go version` in your console

go version go1.20.5 windows/amd64

4.Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```
5. What did you do?

   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.

Using https://github.com/apache/arrow-adbc/blob/main/go/adbc/pkg/snowflake/driver.go, have compiled as a DLL to load to https://github.com/apache/arrow-adbc/tree/main/csharp/src/Apache.Arrow.Adbc (to test the interop of native w/ managed code). The call to ConnectionInit produces the error:

AdbcException: '[Snowflake] AdbcConnectionInit: Go panic in Snowflake driver (see stderr): "assignment to entry in nil map"

The call stack is:

Snowflake driver panicked, stack traces:
goroutine 17 [running, locked to thread]:
main.poison(0x18?, {0x6c56bd7b, 0x12}, {0x6c3de700, 0x6c71e510})
        C:/dev/arrow-adbc/go/adbc/pkg/snowflake/driver.go:97 +0x87
main.SnowflakeConnectionInit.func1()
        C:/dev/arrow-adbc/go/adbc/pkg/snowflake/driver.go:339 +0x51
panic({0x6c3de700, 0x6c71e510})
        C:/Program Files/Go/src/runtime/panic.go:884 +0x213
**github.com/snowflakedb/gosnowflake.(*snowflakeConn).populateSessionParameters(0xc000186fc0, {0xc000695180, 0x22, 0x2a})**
        C:/Users/davidcoe/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.6.23-0.20230616090328-ed37dbc38c55/connection_util.go:164 +0x3d0
github.com/snowflakedb/gosnowflake.authenticateWithConfig(0xc000186fc0)
        C:/Users/davidcoe/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.6.23-0.20230616090328-ed37dbc38c55/auth.go:538 +0x3b8
github.com/snowflakedb/gosnowflake.SnowflakeDriver.OpenWithConfig({}, {_, _}, {{0xc0008cb088, 0x7}, {0xc0008cb098, 0x6}, {0xc0008cb0b0, 0xc}, {0x0, ...}, ...})
        C:/Users/davidcoe/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.6.23-0.20230616090328-ed37dbc38c55/driver.go:43 +0xfe
github.com/snowflakedb/gosnowflake.Connector.Connect({{0x6c72d038, 0x6cf7b248}, {{0xc0008cb088, 0x7}, {0xc0008cb098, 0x6}, {0xc0008cb0b0, 0xc}, {0x0, 0x0}, ...}}, ...)
        C:/Users/davidcoe/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.6.23-0.20230616090328-ed37dbc38c55/connector.go:34 +0xcc
github.com/apache/arrow-adbc/go/adbc/driver/snowflake.(*database).Open(0xc000914480, {0x6c739fe8?, 0xc00002e070?})
        C:/dev/arrow-adbc/go/adbc/driver/snowflake/driver.go:438 +0x1b8
main.SnowflakeConnectionInit(0x5137f7e7c0, 0x0?, 0x5137f7e7a0)
        C:/dev/arrow-adbc/go/adbc/pkg/snowflake/driver.go:355 +0x117

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x1efa7adec18, 0x72)
        C:/Program Files/Go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0x566fabfb1d181a45?, 0xc0006ab6e8?, 0x0)
        C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.execIO(0xc0001b0018, 0x6c5ec8f8)
        C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0xf7
internal/poll.(*FD).Read(0xc0001b0000, {0xc000932000, 0x1800, 0x1800})
        C:/Program Files/Go/src/internal/poll/fd_windows.go:436 +0x2b8
net.(*netFD).Read(0xc0001b0000, {0xc000932000?, 0xc00093200d?, 0x76f?})
        C:/Program Files/Go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000540038, {0xc000932000?, 0x17f3?, 0xc000932005?})
        C:/Program Files/Go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000528060, {0xc000932000?, 0xc000528060?, 0x0?})
        C:/Program Files/Go/src/crypto/tls/conn.go:788 +0x3d
bytes.(*Buffer).ReadFrom(0xc0001b4290, {0x6c723240, 0xc000528060})
        C:/Program Files/Go/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0001b4000, {0x1efa7aded08?, 0xc000540038}, 0x0?)
        C:/Program Files/Go/src/crypto/tls/conn.go:810 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0001b4000, 0x0)
        C:/Program Files/Go/src/crypto/tls/conn.go:617 +0x116
crypto/tls.(*Conn).readRecord(...)
        C:/Program Files/Go/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc0001b4000, {0xc000144000, 0x1000, 0x22?})
        C:/Program Files/Go/src/crypto/tls/conn.go:1316 +0x16f
net/http.(*persistConn).Read(0xc0001a0000, {0xc000144000?, 0xc00054c8a0?, 0xc0006abd30?})
        C:/Program Files/Go/src/net/http/transport.go:1943 +0x4e
bufio.(*Reader).fill(0xc000186a80)
        C:/Program Files/Go/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).Peek(0xc000186a80, 0x1)
        C:/Program Files/Go/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc0001a0000)
        C:/Program Files/Go/src/net/http/transport.go:2107 +0x1ac
created by net/http.(*Transport).dialConn
        C:/Program Files/Go/src/net/http/transport.go:1765 +0x16ea

goroutine 22 [select]:
net/http.(*persistConn).writeLoop(0xc0001a0000)
        C:/Program Files/Go/src/net/http/transport.go:2410 +0xf2
created by net/http.(*Transport).dialConn
        C:/Program Files/Go/src/net/http/transport.go:1766 +0x173d

6. What did you expect to see?

   What should have happened and what happened instead?

   The session parameters should be set, but an error is thrown because the Parameters map was not initialized before setting the values.

7. Can you set logging to DEBUG and collect the logs?

   https://community.snowflake.com/s/article/How-to-generate-log-file-on-Snowflake-connectors
   
8. What is your Snowflake account identifier, if any? (Optional)

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for submitting this issue. at the first glance, I'm not entirely sure whether it's a supported use-case or not, but to take a look, could you please
* add a Go program which when run, leads to the issue
* if you run this program (which reproduces the issue) with gosnowflake but outside of Apache ADBC, does it still fail ? 
* if it doesn't, can you please add the build and reproduction steps? would help tremendously in debugging 
thank you in advance !

**Comment by davidhcoe** [comment]
I discovered the issue was actually in the ADBC Snowflake Go driver, as the db.Config.Params were not being initialized before being passed to the driver.
