### ISSUE TITLE
Add ability to specify / disable temp directory

### ISSUE THREAD

**Issue by mihaitodor** [snowflakedb/gosnowflake#832]
## What is the current behavior?

Currently, users can specify the location where temp files are created via the Go-specific env var `TMPDIR`. The driver needs to write temp files as part of its workflow.

## What is the desired behavior?

We’d like the ability to specify the temp directory used by this driver via a dedicated mechanism, such as the `SNOWFLAKE_TMPDIR` env var instead of relying on Go’s general purpose `TMPDIR` env var. Additionally, it would be great to be able to disable it completely, even if that means disabling some functionality.

## How would this improve `gosnowflake`?

This would allow people to use the driver when the local file system is readonly.

## References, Other Background

This is a follow-up to #700.

**Comment by sfc-gh-dszmolka** [comment]
thank you so much @mihaitodor for creating this follow-up issue; now I can update this properly once there's any new progress on the improvement part

**Comment by sfc-gh-dszmolka** [comment]
#874 aims to implement this functionality.

**Comment by sfc-gh-dszmolka** [comment]
PR has been merged and will be part of the next release, which is expected towards the end of August

**Comment by mihaitodor** [comment]
@sfc-gh-dszmolka Awesome, thank you! Looking at the changes, I'm not sure if this also adds the ability to disable the usage of temp files. Is this something that you're planning to implement in the future?

Also, I think it might be worth documenting this tempdir functionality in https://github.com/snowflakedb/gosnowflake/blob/master/doc.go so people can learn about it via the package docs: https://pkg.go.dev/github.com/snowflakedb/gosnowflake

**Comment by sfc-gh-dszmolka** [comment]
got some update on this one:
1. docs: #884 for the newly implemented feature (ability to specify the temp dir)
2. the driver team has considered the other request too (disabling temp dir usage completely, even at the cost of loss of driver functionality) and for now we decided not to move forward with this request, as it seems to be a non-generic use-case of the gosnowflake connector. Of course this can be re-evaluated any time if more users and customers are asking for it, we will reconsider it then.

Speaking of which, as with any feature request with any Snowflake connector: if you (or the future readers, who would need the ability of disabling the usage of temp directory completely) are already a Snowflake customer, please do speak to your Sales representative and let them know how important this feature would be to you. They have access to certain other aspects of your account, which often can help the product teams to prioritize the requests differently.

Of course we'll still love to hear from the open-source community even if not a Snowflake customer, so please Future Readers: if you have a use-case for this feature (disabling temp dir usage completely, even at the cost of loss of driver functionality), let us know.

**Comment by sfc-gh-pfus** [comment]
Hello @mihaitodor ! Your questions made me to dig deeper. I believe that around PUT/GET support we can do some improvements, apart of giving up temp files, we can also move to more stream-based approach. It would require less memory. We have Q3 already planned, but we will consider to include it into our scope for the next quarters.

**Comment by sfc-gh-dszmolka** [comment]
i also raised #887 so the effort for the second request could be publicly tracked, once it's scheduled. 
we'll use this 832 to track the first request (user-manageable temp directory) which will be released in this month's release.

**Comment by mihaitodor** [comment]
Thank you @sfc-gh-pfus and @sfc-gh-dszmolka! I appreciate that!

**Comment by sfc-gh-dszmolka** [comment]
feature handled in this Issue
> functionality to enable the user to specify temp dir path (implemented this PR)

just got released with version 1.6.24, so closing this one. The other request is tracked separately.
