### ISSUE TITLE
AuthTypeTokenAccessor should not require username and password 

### ISSUE THREAD

**Issue by madisonchamberlain** [snowflakedb/gosnowflake#843]
I am using the `AuthTypeTokenAccessor` config type to create a snowflake connection. This does not work if the original connection was an oauth connection, but it should and it does work with a very small change. Here is the code/configs that gets used if the token accessor method is used. (see auth.go)

```
case AuthTypeTokenAccessor:
		logger.Info("Bypass authentication using existing token from token accessor")
		sessionInfo := authResponseSessionInfo{
			DatabaseName:  sc.cfg.Database,
			SchemaName:    sc.cfg.Schema,
			WarehouseName: sc.cfg.Warehouse,
			RoleName:      sc.cfg.Role,
		}
		token, masterToken, sessionID := sc.cfg.TokenAccessor.GetTokens()
		return &authResponseMain{
			Token:       token,
			MasterToken: masterToken,
			SessionID:   sessionID,
			SessionInfo: sessionInfo,
		}, nil
	}
```
But then in fillMissingConfigParameters in dsn.go, username and password are required for the authTokenAccesorType even though they aren't used. To fix this, the code chunk that checks password and username just need to be changed to 

```
if cfg.Authenticator != AuthTypeOAuth &&
	cfg.Authenticator != AuthTypeTokenAccessor &&
	strings.Trim(cfg.User, " ") == "" {
	// oauth and token accessor do not require a username
	return ErrEmptyUsername
}

if cfg.Authenticator != AuthTypeExternalBrowser &&
		cfg.Authenticator != AuthTypeOAuth &&
		cfg.Authenticator != AuthTypeJwt &&
		cfg.Authenticator != AuthTypeTokenAccessor &&
		strings.Trim(cfg.Password, " ") == "" {
		// no password parameter is required for EXTERNALBROWSER, OAUTH JWT, or TOKENACCESSOR.
		return ErrEmptyPassword
}
```

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this issue, and really appreciate sharing the findings and the proposed solution too ! we'll take a look.

**Comment by sfc-gh-dszmolka** [comment]
#846

**Comment by sfc-gh-dszmolka** [comment]
reopening so we could properly track together with the driver release, which is expected to happen towards the end of July. fix will be part of that.
