### ISSUE TITLE
getSnowflakeType() could be more efficient

### ISSUE THREAD

**Issue by Yifeng-Sigma** [snowflakedb/gosnowflake#881]
https://github.com/snowflakedb/gosnowflake/blob/ad2d6fef32718c982faec3ae99a83dc297b1c8ab/datatype.go#L47-L53

why not use a map here to have O(1) lookup?

**Comment by sfc-gh-dszmolka** [comment]
hello and thank you for raising this issue. could you please elaborate what exact issue the current implementation is causing to you, or why the suggested new approach would be preferred ?

if applicable, we would also very much appreciate a relevant code snippet which when run, exhibits the issue you found. 

thank you very much in advance !

**Comment by sfc-gh-dszmolka** [comment]
#890

**Comment by sfc-gh-dszmolka** [comment]
apparently the PR is merged :) reopening this issue to be able to track that it will be part of the _next_ release, coming towards end of September

**Comment by sfc-gh-dszmolka** [comment]
released with [1.6.25](https://github.com/snowflakedb/gosnowflake/tree/v1.6.25)
