### ISSUE TITLE
Zombie dbus processes generated by github.com/99designs/keyring

### ISSUE THREAD

**Issue by biazmoreira** [snowflakedb/gosnowflake#901]
Referencing/re-opening the issue https://github.com/snowflakedb/gosnowflake/issues/773: 

> `gosnowflake` added https://github.com/99designs/keyring as a dependency and, unfortunately, this library has an https://github.com/99designs/keyring/issues/103 which can lead some Linux systems to create zombie dbus processes. This issue was observed initially when importing the Apache Pulsar client library into Benthos as described https://github.com/benthosdev/benthos/issues/1184 and it's triggered in one of the init() functions from github.com/99designs/keyring.

This is causing Vault to run into the fs.inotify.max_user_instances limit or fd limits causing issues for systemd. See https://github.com/hashicorp/vault/issues/22560

**Comment by sfc-gh-dszmolka** [comment]
reopened #773 , closing this one as a duplicate. Please work with us on #773. Thank you for reporting this issue !
