### ISSUE TITLE
arrowToRecord() produce wrong timestamp for some future dates 

### ISSUE THREAD

**Issue by Yifeng-Sigma** [snowflakedb/gosnowflake#910]
Super easy to reproduce, 

https://github.com/sigmacomputing/gosnowflake/blob/17fd0144860b6ee0164c398488ad9fa02fb65f36/converter_test.go#L850
change year to >= 2263 or <= 1677 and the the unit test will fail.
While per documentation it's within the range "Snowflake recommends using years between 1582 and 9999".

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for submitting this issue with us, we'll take a look

**Comment by sfc-gh-dszmolka** [comment]
PR https://github.com/snowflakedb/gosnowflake/pull/918 with the fix in progress. Thank you for bearing with us while this is getting fixed !

**Comment by sfc-gh-dszmolka** [comment]
PR merged and will be part of the October release, expected towards the end of October

**Comment by sfc-gh-dszmolka** [comment]
gosnowflake 1.7.0 released with the fix, thank you all for bearing with us !

**Comment by madisonchamberlain** [comment]
Hello, I am wondering if there are any recommendations on how `ArrowSnowflakeTimestampToTime` should be used.

**Comment by sfc-gh-dszmolka** [comment]
hi there - we seem to have some in [converter_test.go](https://github.com/snowflakedb/gosnowflake/blob/v1.7.2/converter_test.go); would that suffice as an example or should we provide something more ?

**Comment by Yifeng-Sigma** [comment]
> hi there - we seem to have some in [converter_test.go](https://github.com/snowflakedb/gosnowflake/blob/v1.7.2/converter_test.go); would that suffice as an example or should we provide something more ?

@sfc-gh-dszmolka Thank you, this is helpful. One more question:
Is it possible for you to provide timestamp in microsecond precision? microsecond should be able to fit in `arrow.Timestamp` without the need of using arrow.Struct. 
In our use case, the connector passes the arrow record from Snowflake to another service for decoding. If we have microsecond precision, we can avoid the need to port the arrowSnowflakeTimestampToTime logic.

**Comment by sfc-gh-dszmolka** [comment]
(responded internally)
