### ISSUE TITLE
Getting an error when using PUT command

### ISSUE THREAD

**Issue by dms1122** [snowflakedb/gosnowflake#920]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of GO driver are you using?
1.6.25
   
2. What operating system and processor architecture are you using?
RH9
   
3. What version of GO are you using?
run `go version` in your console
go version go1.21.1 linux/amd64

4.Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```
7.34.0

5. What did you do?

db.Query("PUT file://tmp/tmp.json @TEST_STAGE")

And got this error:

DB query error: 091003 (22000): Failure using stage area. Cause: [TEST_STAGE GET and PUT commands are not supported with external stage]

6. What did you expect to see?

A file to be uploaded to a SF stage. As per the doc PUT command is supported.

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for submitting this issue! per Snowflake documentation at https://docs.snowflake.com/en/sql-reference/sql/put, GET and PUT only supported for:
> * Named internal stage.
> * Internal stage for a specified table.
> * Internal stage for the current user.

if TEST_STAGE is an external stage, please use the cloud provider's relevant CLI or GUI tools to upload files there. To confirm the correct operation, can you please 
1. create an internal stage: `create stage my_other_stage`
2. execute your program to put file into this stage: `db.Query("PUT file://tmp/tmp.json @MY_OTHER_STAGE")`

this should work fine, as `my_other_stage` (a named internal stage) is a Snowflake-internal one, on which PUT and GET is supported, as opposed to the external ones which you create over your self-managed cloud storage blobs.

let me know please how this went.

**Comment by dms1122** [comment]
@sfc-gh-dszmolka  tested it for an internal stage, it works. Thank you for your quick response, closing the issue.
