### ISSUE TITLE
Support Describe Only through SnowflakeConn

### ISSUE THREAD

**Issue by CurtHagenlocher** [snowflakedb/gosnowflake#954]
## What is the current behavior?
As a result of changes made for #424, "describe only" support was added to API functions such as ExecContext and QueryContext. When QueryArrowStream was later added for #781, it did not include "describe only" support. This means that consumers who would otherwise prefer to get schema information in the same format as that exposed by QueryArrowStream must instead use e.g. the RowsColumnTypeDatabaseTypeName and RowsColumnTypePrecisionScale interfaces to get similar information. This is both inconvenient and lacking a straightforward way to get the timezone on the server.

## What is the desired behavior?
Be able to get the output schema for a SQL query in the same format as QueryArrowStream without having to produce the query output on the server.

## How would this improve `gosnowflake`?
This will allow the ADBC driver (which consumes gosnowflake) to implement AdbcExecuteSchema.

## References, Other Background
https://github.com/apache/arrow-adbc/issues/1254

## What is your Snowflake account identifier, if any?
N/A

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for the contribution on the PR and especially raising the issue counterpair :) we'll take a look

**Comment by sfc-gh-dszmolka** [comment]
PR #955 is merged, so this one will be part of the next upcoming release
